### PR TITLE
Fix incorrect assertions

### LINKED ISSUE #1247: Using DoctrineDataCollector with EntityManagerDecorator fails
version: 2.2.x 
symfony environment: DEV or TEST with profiler enabled

This assert fails when I use custom EntityManagerDecorator:

https://github.com/doctrine/DoctrineBundle/blob/2aacd8380030fb2497a896fe33aaa5b1052feccc/DataCollector/DoctrineDataCollector.php#L67

After changing to:

`assert($em instanceof EntityManagerInterface);`

everything seems to be ok.

### PR DESCRIPTION
**Pull request by pkly**
Fixes #1247

### CODE REVIEW

File: DoctrineBundle.php [hunk 1]
```diff
@@ -78,7 +77,7 @@ public function boot()
                 assert($registry instanceof Registry);
 
                 foreach ($registry->getManagers() as $em) {
-                    assert($em instanceof EntityManager);
+                    assert($em instanceof EntityManagerInterface);
```
Comment (dmaicher) [inline DoctrineBundle.php:80]: I don't see any `use` statement for this one?

Comment (pkly) [reply DoctrineBundle.php:81]: Yep, my bad. Storm decided not to remind me.

**Review by SenseException — APPROVED** [review]

File: DataCollector/DoctrineDataCollector.php [hunk 2]
```diff
@@ -101,7 +101,7 @@ public function collect(Request $request, Response $response, Throwable $excepti
             $cacheConfiguration = $emConfig->getSecondLevelCacheConfiguration();
             assert($cacheConfiguration instanceof CacheConfiguration);
             $cacheLoggerChain = $cacheConfiguration->getCacheLogger();
-            assert($cacheLoggerChain instanceof CacheLoggerChain);
+            assert($cacheLoggerChain instanceof CacheLoggerChain || $cacheConfiguration === null);
```
Comment (stof) [inline DataCollector/DoctrineDataCollector.php:104]: Instead of the assert, the `if (! $cacheLoggerChain)` below could be changed to `! $cacheLoggerChain instanceof CacheLoggerChain)` (which would also cover a case where a custom CacheLogger is passed without using a chain)

Comment (ostrolucky) [reply DataCollector/DoctrineDataCollector.php:104]: I don't like that because it would silence the error in case of unexpected instance.

Comment (stof) [reply DataCollector/DoctrineDataCollector.php:104]: The thing is, the data collector is not in charge of configuring the cache logger. If the debugging tool breaks entirely because you customized the config in a way that they did not expect, that's quite bad. It seems better to skip the SLC stats in such case.

Comment (ostrolucky) [reply DataCollector/DoctrineDataCollector.php:104]: I'm more proponent of [offensive programming](https://en.wikipedia.org/wiki/Offensive_programming) and there it's better to crash than display incorrect information.
