### PR TITLE
Fix position of `$enableXsdValidation` in `DoctrineOrmMappingsPass::createXmlMappingDriver`

### LINKED ISSUE #2189: [3.2] BC Break in DoctrineOrmMappingsPass::createXmlMappingDriver signature causing conflicts with ecosystem bundles
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 3.2

#### Summary

I am upgrading my project to doctrine/doctrine-bundle ^3.0 and encountered a breaking change that causes compatibility issues with other Symfony bundles (specifically web-auth/webauthn-symfony-bundle).

In version 3.2, the $aliasMap argument was removed (https://github.com/doctrine/DoctrineBundle/commit/1b5a951989bacf01df4b8057ade4f9202d20aeca#diff-deac0dc9c56580dc9ccd479560e2fa41eb2c3b4705ba737858cf2b7862a349f2L64) from the createXmlMappingDriver method signature in Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass.

#### Current behavior

Existing bundles that support older Doctrine versions call this method with 5 arguments (passing [] for $aliasMap). This results in a fatal error in DoctrineBundle 3.2 because the 4th argument is now expected to be bool $enableXsdValidation, but receives an array, and the method receives too many arguments.

`TypeError: Doctrine\Bundle\DoctrineBundle\DependencyInjection\Compiler\DoctrineOrmMappingsPass::createXmlMappingDriver(): Argument #4 ($enableXsdValidation) must be of type bool, array given`

#### Expected behavior

Was this hard break intended without a compatibility layer? It makes upgrading difficult as we have to wait for the entire ecosystem to tag releases strictly compatible with DoctrineBundle 3.x. Would you consider restoring the argument (even if unused/deprecated) to maintain signature compatibility?

### PR DESCRIPTION
**Pull request by KDederichs**
Fix by allowing $enableXsdValidation to contain an array. If it does trigger a deprecation and grab the correct $enableXsdValidation parameter via func_get_arg

Fixes #2189

### CODE REVIEW

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php [hunk 1]
```diff
@@ -47,17 +52,27 @@ public function __construct(Definition|Reference $driver, array $namespaces, arr
...
-     *                                        optional.
+     * @param string[]      $namespaces          Hashmap of directory path to namespace.
+     * @param string[]      $managerParameters   List of parameters that could which object manager name
+     *                                           your bundle uses. This compiler pass will automatically
+     *                                           append the parameter name for the default entity manager
+     *                                           to this list.
+     * @param string|false  $enabledParameter    Service container parameter that must be present to
+     *                                           enable the mapping. Set to false to not do any check,
+     *                                           optional.
+     * @param string[]|bool $enableXsdValidation This should never be an array, but is is due to BC reasons.
```
Comment (GromNaN) [inline src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: Only the expected type should be documented, for static analysis.
```suggestion
     * @param bool $enableXsdValidation
```

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php [hunk 2]
```diff
@@ -47,17 +52,27 @@ public function __construct(Definition|Reference $driver, array $namespaces, arr
...
      */
-    public static function createXmlMappingDriver(array $namespaces, array $managerParameters = [], string|false $enabledParameter = false, bool $enableXsdValidation = false): self
+    public static function createXmlMappingDriver(array $namespaces, array $managerParameters = [], string|false $enabledParameter = false, bool|array $enableXsdValidation = false): self
     {
+        if (is_array($enableXsdValidation)) {
+            trigger_deprecation('doctrine/doctrine-bundle', '3.2', 'Starting version 3.2 passing $aliasMap to createXmlMappingDriver is deprecated and has no effect.');
```
Comment (GromNaN) [inline src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: Doctrine has the `doctrine/deprecations` package. The function `trigger_deprecation` is provided by `symfony/deprecation-contracts`.


```suggestion
            \Doctrine\Deprecations\Deprecation::trigger(
                'doctrine/doctrine-bundle',
                'https://github.com/doctrine/DoctrineBundle/pull/2190',
                'Providing a $aliasMap to createXmlMappingDriver is deprecated and has no effect."
            );
```

**Review by GromNaN — COMMENTED** [review]
Thanks for the PR.
A few changes to comply with doctrine standards, but it seems correct to me.

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php (hunk 1 above)
Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: PHPStan complains if I just use bool here, that's why I did it that way. (See the PHPStan error)
Not sure if you can just ignore that error somehow or if it should be PHPStan compliant with the message.

Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: @GromNaN I added a phpstan ignore directive to suppress this now which seems to make the tests run fine. I hope that works with the coding standards because I don't see how that's solved otherwise

**Review by GromNaN — APPROVED** [review]

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php [hunk 3]
```diff
@@ -47,17 +52,33 @@ public function __construct(Definition|Reference $driver, array $namespaces, arr
...
+        if (is_array($enableXsdValidation)) {
+            Deprecation::trigger(
+                'doctrine/doctrine-bundle',
+                'https://github.com/doctrine/DoctrineBundle/pull/2190',
+                'Providing a $aliasMap to createXmlMappingDriver is deprecated and has no effect.',
+            );
+            $enableXsdValidation = false;
+
+            if (func_num_args() === 5) {
+                $enableXsdValidation = func_get_arg(4);
```
[the remark this answers is not in the document]
Comment (greg0ire) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: This looks like sweeping the issue under the rug, to be frank.

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php [hunk 4]
```diff
@@ -47,17 +52,33 @@ public function __construct(Definition|Reference $driver, array $namespaces, arr
...
+     * @phpstan-ignore     missingType.iterableValue
      */
-    public static function createXmlMappingDriver(array $namespaces, array $managerParameters = [], string|false $enabledParameter = false, bool $enableXsdValidation = false): self
+    public static function createXmlMappingDriver(array $namespaces, array $managerParameters = [], string|false $enabledParameter = false, bool|array $enableXsdValidation = false): self
     {
+        if (is_array($enableXsdValidation)) {
+            Deprecation::trigger(
+                'doctrine/doctrine-bundle',
+                'https://github.com/doctrine/DoctrineBundle/pull/2190',
+                'Providing a $aliasMap to createXmlMappingDriver is deprecated and has no effect.',
```
Comment (greg0ire) [inline src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]:
```suggestion
                'Providing a $aliasMap argument to createXmlMappingDriver() is deprecated and has no effect.',
```

Comment (greg0ire) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: You could use `__METHOD__`

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: You actually want to apply that one? IMO makes little sense if we're just trying to keep BC of existing bundles.
It should throw errors in peoples faces if they try to pass weird stuff there.

[the remark this answers is not in the document]
Comment (greg0ire) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: What in my message could possibly make you think I want to apply that one?

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php [hunk 5]
```diff
@@ -47,17 +52,33 @@ public function __construct(Definition|Reference $driver, array $namespaces, arr
...
+     * @phpstan-ignore missingType.iterableValue
      */
-    public static function createXmlMappingDriver(array $namespaces, array $managerParameters = [], string|false $enabledParameter = false, bool $enableXsdValidation = false): self
+    public static function createXmlMappingDriver(array $namespaces, array $managerParameters = [], string|false $enabledParameter = false, bool|array $enableXsdValidation = false): self
     {
+        if (is_array($enableXsdValidation)) {
+            Deprecation::trigger(
+                'doctrine/doctrine-bundle',
+                'https://github.com/doctrine/DoctrineBundle/pull/2190',
+                'Providing a $aliasMap argument to createXmlMappingDriver() is deprecated and has no effect.',
```
Comment (greg0ire) [inline src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: Please use `__METHOD__`

Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: Sorry not quite sure what you mean by that.
Is it like a placeholder for createXmlMappingDriver() ?

Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: Ok got it after looking at the rest of the doctrine codebase

File: src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: It was more of a question tbh.
But yeah just ignoring that then

[the remark this answers is not in the document]
Comment (GromNaN) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: @greg0ire I don't understand your message. Do you think there is a better way to resolve the issue?

[the remark this answers is not in the document]
Comment (greg0ire) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: What I am saying is that copilot is suggesting we silently ignore non booleans, and I think that's a terrible suggestion.

[the remark this answers is not in the document]
Comment (greg0ire) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: A better solution IMO would be to throw a type error when the type is not one of the expected types

[the remark this answers is not in the document]
Comment (KDederichs) [reply src/DependencyInjection/Compiler/DoctrineOrmMappingsPass.php]: @greg0ire I added a bool type check that throws an error if a non bool is found, could you please check if this/the error message is alright with you?

**Review by greg0ire — APPROVED** [review]
