### PR TITLE
Fix explaining queries

### LINKED ISSUE #757: [Profiler] Explain is broken
Hitting the "Explain query" link in the Doctrine's profiler screen reports "An error occurred while loading the query explanation." with request to profiler controller reporting 500 status.

It's caused by `vendor/doctrine/doctrine-bundle/Controller/ProfilerController.php:102`
```php
    private function explainOtherPlatform(Connection $connection, $query)
    {
        return $connection->executeQuery('EXPLAIN '.$query['sql'], $query['params'], $query['types'])
            ->fetchAll(\PDO::FETCH_ASSOC);
    }
```

The second parameter of `executeQuery()` must be an array while `$query['params']` is an instance of `Symfony\Component\VarDumper\Cloner\Data`.

### PR DESCRIPTION
**Pull request by stof**
Recent Symfony versions are wrapping the params in a VarDumper Data when collecting the profiler info. This ensures that they get unwrapped properly when trying to explain the query.

Fixes #757

### CODE REVIEW

**Comment by stof** [comment]
Recent means at least 3.4+. I don't remember about older 3.x versions (and I don't have any project using these older unmaintained 3.x versions to test)

File: Controller/ProfilerController.php [hunk 1]
```diff
@@ -77,14 +78,27 @@ private function explainSQLServerPlatform(Connection $connection, $query)
         } else {
             $sql = 'SET SHOWPLAN_TEXT ON; GO; SET NOEXEC ON; ' . $query['sql'] . '; SET NOEXEC OFF; GO; SET SHOWPLAN_TEXT OFF;';
         }
-        $stmt = $connection->executeQuery($sql, $query['params'], $query['types']);
+
+        $params = $query['params'];
+
+        if ($params instanceof Data) {
```
Comment (mikeSimonson) [inline Controller/ProfilerController.php]: Can you create a function with an explicit name and call it in both place ?

**Comment by kimhemsoe** [comment]
@stof Is it possible to add a test for it?

**Comment by stof** [comment]
The proper way to test this in a way making the test strong a regarding changes in the bridge collector would involve building a fake app running some DB query, and having a functional test running a request on this fake app, then opening the profiler, and then trying to explain the query in it (by loading the URL of the partial). This would involve a bunch of work, and I won't have time to work on this during the next few days (and I cannot guarantee it for the next few weeks, even though the French holidays coming in May may give me time for it, but in conflict with other OSS stuff). Is it required to build such test covering the profiler explaining feature for the bug fix to be merged ?

**Comment by kimhemsoe** [comment]
I will merge in now then. I very much would a test for this if you or someone else find the time to todo it :)

**Comment by kimhemsoe** [comment]
it is a long running bug, so lets fix it for now and then we can clean up the mess later...

@stof Thanks

**Comment by hvt** [comment]
Would be great if a release could be made that includes this PR.
