### PR TITLE
Remap collate to collation when appropriate

### LINKED ISSUE #470: doctrine:migrations:diff generates diff for the field with enumType
Hi all!

I have an Entity

```
/**
 * @ORM\Entity
 * @ORM\Table(
 *     name="daily_sale_aggregations"
 * )
 */
class DailyAggregation implements Entity
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private int $id;
    
    /**
     * @ORM\Column(type="string", enumType="Planning\Application\Enum\SaleTypeEnum", options={"default" : "total"})
     */
    private SaleTypeEnum $saleType;
}
```

And whem I run `bin/console doctrine:migrations:diff` I always have new migration created:
```
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_sale_aggregations CHANGE sale_type sale_type VARCHAR(255) DEFAULT \'total\' NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE daily_sale_aggregations CHANGE sale_type sale_type VARCHAR(255) CHARACTER SET utf8 DEFAULT \'total\' NOT NULL COLLATE `utf8_unicode_ci`');
    }
```

Libraries used
"doctrine/doctrine-migrations-bundle": "^3.2",
"doctrine/orm": "^2.11"

Is it an issue or I'm doing something wrong?

### LINKED ISSUE #1240: generating new migrations creates the same junk in the down() method every time
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | i don't know
| Version     | 3.4.1 (doctrine-migrations-bundle 3.2.1)

#### Current behavior

Firstly, it used to be the case that `./bin/console doctrine:migrations:diff` would not generate anything if the database schema was in sync.  I am not sure if perhaps that behavior was changed, but in my current state running this command always generates a migrations file.  I can run it 10 times in a row and it will create 10 migrations files with blank `up()` method bodies.

Secondly, every time I generate a migration file, it always includes the same spam in the `down()` method. I've run multiple generated migration files since this behavior started, and its continues to persist (running migrations shouldn't fix the problem anyway, as this is a problem in the `down()` method, not `up()`.

Here is an example of the spam:

```
public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE table_one CHANGE description description LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE short short VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE table_two CHANGE type type VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
        ....
    }
```
There are dozens of `addSql()` statements, I've just included a few for brevity.  They all follow this same pattern related to `utf8` and `utf8_general_ci`.

#### How to reproduce

I don't know specific steps, this is happening every time I generate a migration file, the same spam in `down()` each time.

### LINKED ISSUE #1468: Configuration for collation in default table options (collate/collation)
In some places in this bundle and DBAL `collate` is used, in some other places `collation` is used. https://github.com/doctrine/dbal/issues/5214

I need to put both in my config:
```yaml
doctrine:
    dbal:
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_0900_ai_ci
            collate: utf8mb4_0900_ai_ci
```

If I only use `collate` (it worked before updating DBAL from 3.2.1 to 3.3.1), schema comparator, which uses `collation` config, detects changes and generates weird migrations when executing `doctrine:migrations:diff` command: empty `up()` and a `down()` full of useless ALTER TABLE.

If I only use `collation`, it creates new tables with `utf8mb4_unicode_ci` collation.

I know DBAL v4 won't force any charset/collation, but still the config documentation feels wrong...
https://github.com/doctrine/DoctrineBundle/blob/2.5.x/Resources/doc/configuration.rst

### PR DESCRIPTION
**Pull request by greg0ire**
`collate` was never supposed to be supported and used in the first place,
and DBAL 3.3.2 fixed that.
Here, we avoid the situation where a user willing to use the correct
option ends up with both `collate` and `collation` defined, and we remap
`collate` to `collation` when DBAL 3.3 is detected. DBAL 3.3.0 and 3.3.1 are
avoided thanks to a composer version constraint.

Might fix #1468 , might also fix https://github.com/doctrine/migrations/issues/1240, and might also fix https://github.com/doctrine/DoctrineMigrationsBundle/issues/470

# How can I test this?

```shell
composer config repositories.greg0ire vcs https://github.com/greg0ire/DoctrineBundle
composer require doctrine/doctrine-bundle "dev-collation as 2.5.5"
```

### CODE REVIEW

**Comment by greg0ire** [comment]
@aprat84 @dmaicher @natewiebe13 @floviolleau please test

**Comment by bobvandevijver** [comment]
Tested this as I found the same behaviour described in https://github.com/doctrine/dbal/issues/5243, it doesn't change anything. However, changing the `collate` option in the dbal configuration to `collation` does solve the issue for me, and that doesn't need this change.

**Comment by natewiebe13** [comment]
Similar experience here. Using this branch using `collate` produces the down with unexpected queries, using `collation` doesn't produce a migration.

**Comment by natewiebe13** [comment]
Also, it's probably worth updating the older recipes (provided they support `collation`) and very likely the config reference in the docs.

Refs:
- https://github.com/doctrine/DoctrineBundle/blob/2.5.x/Resources/doc/configuration.rst
- https://github.com/doctrine/DoctrineBundle/blob/2.5.x/DependencyInjection/Configuration.php
- https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.6/config/packages/doctrine.yaml
- https://github.com/symfony/recipes/blob/master/doctrine/doctrine-bundle/1.12/config/packages/doctrine.yaml

**Comment by greg0ire** [comment]
@natewiebe13 that should be done in a follow-up PR targeting 2.6.x: this one is not about the public interface of DoctrineBundle, but about adapting to the public interface of `doctrine/dbal` in the least disrupting way.

I'm noting that this improves your experience only when switching to `collation`, but I don't understand why it does not change anything when you use `collate`. I don't experience that issue myself so if you can debug this and find out what's happening, that would be great.

**Comment by natewiebe13** [comment]
@greg0ire I've updated by test project here: https://github.com/natewiebe13/doctrine-dbal-bug

This is likely the way most Symfony projects are configured, as it was at one time either suggested through a recipe/recommended through docs. Specifically this: https://github.com/natewiebe13/doctrine-dbal-bug/commit/c8344891f67dfc4b195e3a302baaefcf3ab549a9

What's happening is because of the logic on the parent if statement, the path completely skips the logic you added and directly inputs the configuration into here: https://github.com/doctrine/DoctrineBundle/blob/2.5.x/ConnectionFactory.php#L98

**Comment by greg0ire** [comment]
Ok, so this means this bundle is not involved at all in the bug you are experiencing with this project, right?

**Comment by natewiebe13** [comment]
Based on the example I provided, that's my thinking as well in terms of the bundle's involvement in configuring the dbal connection. That being said, it is unfortunate that the change in doctrine/dbal is causing this to happen.

Do you think it's worth adding a conflicts with dbal > 3.3.0 and then resolving that in 2.6 or something? I'm just wondering if there's a way to make it more obvious for people that run into this without it triggering new issues being created.

**Comment by greg0ire** [comment]
I don't think it's worth it, IMO it might just prevent people from upgrading the DoctrineBundle.

**Comment by pps1** [comment]
+1 on this fix @greg0ire

After your patch `diff` no longer generates empty `up` and false `down` statements that do not introduce any changes to the existing schema.

```
doctrine:

  dbal:
    # https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration
    dbname: '%env(resolve:DATABASE_NAME)%'
    host: '%env(resolve:DATABASE_HOST)%'
    port: '%env(resolve:DATABASE_PORT)%'
    user: '%env(resolve:DATABASE_USER)%'
    password: '%env(resolve:DATABASE_ROOT_PASSWORD)%'
    server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'

  orm:
    auto_generate_proxy_classes: true
    //{...}
```

```
--
-- Table structure for table `address`
--

DROP TABLE IF EXISTS `address`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `address` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `guid` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '(DC2Type:guid)',
  `address1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address1_blind_idx` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address2_blind_idx` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `city` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `state_or_province` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `postal_code` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `country_code` varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL,
  `telephone_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telephone_number_blind_idx` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fax_number_blind_idx` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `purpose` smallint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_D4E6F812B6FCFB2` (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```

```
final class Version20220212202808 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE address CHANGE address1 address1 VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE address1_blind_idx address1_blind_idx VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE address2 address2 VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE address2_blind_idx address2_blind_idx VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(64) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE state_or_province state_or_province VARCHAR(64) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE postal_code postal_code VARCHAR(24) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE country_code country_code VARCHAR(2) NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE telephone_number telephone_number VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE telephone_number_blind_idx telephone_number_blind_idx VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE fax_number fax_number VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE fax_number_blind_idx fax_number_blind_idx VARCHAR(255) DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE guid guid CHAR(36) DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\'');
//{...}
    }
}
```

File: ConnectionFactory.php [hunk 1]
```diff
@@ -79,8 +80,14 @@ public function createConnection(array $params, ?Configuration $config = null, ?
                 if ($driver instanceof AbstractMySQLDriver) {
                     $params['charset'] = 'utf8mb4';
 
-                    if (! isset($params['defaultTableOptions']['collate'])) {
-                        $params['defaultTableOptions']['collate'] = 'utf8mb4_unicode_ci';
+                    if (isset($params['defaultTableOptions']['collate']) && defined('Doctrine\DBAL\Connection::PARAM_ASCII_STR_ARRAY')) {
```
Comment (derrabus) [inline ConnectionFactory.php:88]: Checking for that constant looks a bit odd at first. We should leave a comment here, explaining that we're trying to detect the DBAL version here.

File: composer.json [hunk 2]
```diff
@@ -28,7 +28,7 @@
         "php": "^7.1 || ^8.0",
         "doctrine/annotations": "^1",
         "doctrine/cache": "^1.11 || ^2.0",
-        "doctrine/dbal": "^2.13.1|^3.1",
+        "doctrine/dbal": "^2.13.1|^3.3.2",
```
Comment (derrabus) [inline composer.json:31]: Since you're targeting the 2.5 branch: Are we sure we want to do this kind of bump in a bugfix release?

Comment (greg0ire) [reply composer.json:31]: I think it's OK since only 3.3 is supported.

Comment (greg0ire) [reply composer.json:31]: But I'm not sure what's the policy on this. Maybe @ostrolucky does?

Comment (ostrolucky) [reply composer.json:31]: I don't mind

**Review by ostrolucky — APPROVED** [review]

**Comment by arderyp** [comment]
@greg0ire @ostrolucky was this included in the latest 2.5.6 release earlier today?  If so, I am unfortunately still experiencing problems with junk being generated in my `down()` method ([original report](https://github.com/doctrine/migrations/issues/1240) I made on the wrong repo)

**Comment by natewiebe13** [comment]
@arderyp see my comment here: https://github.com/doctrine/DoctrineBundle/pull/1471#issuecomment-1035008043

Potentially you're running into this as well. tldr; if you're configuring dbal's collate option directly, you must change the configuration to use `collation` instead.

**Comment by arderyp** [comment]
thanks for the quick reply @natewiebe13.  Am I understanding correctly from your comment that the solution is to define "server_version" in the `dbal` config?  If so, I am still running into issues on `2.5.6`:

this produces an error from `bin/console doctrine:migrations:diff`: "Unrecognized option "server_version" under "doctrine.dbal". Available options are "connections", "default_connection", "types"."

```
doctrine:
  dbal:
    default_connection: default
    server_version: '8.0'
    connections:
      default:
        charset:  UTF8
        driver:   pdo_mysql
        host:     '%env(DATABASE_HOST)%'
        port:     '%env(DATABASE_PORT)%'
        dbname:   '%env(DATABASE_NAME)%'
        user:     '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
```

this produces the same junk in `down()`
```
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        charset:  UTF8
        driver:   pdo_mysql
        server_version: '8.0'
        host:     '%env(DATABASE_HOST)%'
        port:     '%env(DATABASE_PORT)%'
        dbname:   '%env(DATABASE_NAME)%'
        user:     '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
```

Adding the following didn't help:

```
charset: utf8mb4
      default_table_options:
          charset: utf8mb4
          collate: utf8mb4_unicode_ci
```

```
charset: utf8mb4
      default_table_options:
          charset: utf8mb4
          collation: utf8mb4_unicode_ci
```

**Comment by natewiebe13** [comment]
I'm not familiar enough with configuring connections in that way to give you much direction. It might be worth a new issue or following up on the previous one.

**Comment by greg0ire** [comment]
> What's happening is because of the logic on the parent if statement, the path completely skips the logic you added and directly inputs the configuration into here

@natewiebe13 so… your driver is not an `AbstractMySQLDriver` :thinking: :thinking: :thinking: ?

**Comment by arderyp** [comment]
@natewiebe13 for what it is worth, these more straightforward dbal configs also don't solve the problem:

```
doctrine:
  dbal:
    server_version: '8.0'
    driver: 'pdo_mysql'
    charset: UTF8
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
```

```
doctrine:
  dbal:
    server_version: '8.0'
    driver: 'pdo_mysql'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collation: utf8mb4_unicode_ci
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
```

**Comment by greg0ire** [comment]
@natewiebe13 ah I see, you mean this if statement: https://github.com/doctrine/DoctrineBundle/blob/f1423b2a640b6ac545b6e0c02575427a4dc1e9dc/ConnectionFactory.php#L59

**Comment by natewiebe13** [comment]
@greg0ire correct. https://github.com/doctrine/DoctrineBundle/blob/2.5.x/ConnectionFactory.php#L59

**Comment by greg0ire** [comment]
So doing the remapping outside that condition would improve your experience further I think, but I don't know that it would fix @arderyp 's issue, and since you already have a good solution (switching to `collation`), I'm not sure if it is worth it.

**Comment by arderyp** [comment]
@greg0ire maybe I am not tracking the discussion well (some of this is over my head), but the `collation` bit doesn't seem to work for me. Unless my sample configs above don't appear to be doing it properly?

**Comment by greg0ire** [comment]
Honestly I don't have any idea what could be happening to you. If I were you, I'd look for all places in `vendor/doctrine` where `collate` appears and then add breakpoints there to see if I go through it.

**Comment by arderyp** [comment]
thanks @greg0ire I will try to look into that

**Comment by arderyp** [comment]
Maybe you all can help push me in the right direction.

I am comparing a `var_dump` of `$fromSchema` to `$toSchema` in `DiffGenerator`: https://github.com/doctrine/migrations/blob/3.4.x/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L93-L97

I took an example table alteration from my junk `down()` and compared it's definitions in the two schemas, and then compared those to my actual SQL definition:

```
###################
### DBAL CONFIG ###
###################
doctrine:
  dbal:
    charset: UTF8
    driver: pdo_mysql
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'


############
### FROM ###
############
object(Doctrine\DBAL\Schema\Schema)#6572 (7) {
  ["namespaces":"Doctrine\DBAL\Schema\Schema":private]=>
  array(0) {
  }
  ["_tables":protected]=>
  array(63) {
    ["app.table"]=>
    object(Doctrine\DBAL\Schema\Table)#6568 (11) {
      ["_columns":protected]=>
      array(6) {
        
        ["description"]=>
        object(Doctrine\DBAL\Schema\Column)#590 (16) {
          ["_type":protected]=>
          object(Doctrine\DBAL\Types\TextType)#760 (0) {
          }
          ["_length":protected]=>
          int(0)
          ["_precision":protected]=>
          int(10)
          ["_scale":protected]=>
          int(0)
          ["_unsigned":protected]=>
          bool(false)
          ["_fixed":protected]=>
          bool(false)
          ["_notnull":protected]=>
          bool(true)
          ["_default":protected]=>
          NULL
          ["_autoincrement":protected]=>
          bool(false)
          ["_platformOptions":protected]=>
          array(2) {
            ["charset"]=>
            string(4) "utf8"
            ["collation"]=>
            string(15) "utf8_general_ci"
          }
          ["_columnDefinition":protected]=>
          NULL
          ["_comment":protected]=>
          NULL
          ["_customSchemaOptions":protected]=>
          array(0) {
          }
          ["_name":protected]=>
          string(11) "description"
          ["_namespace":protected]=>
          NULL
          ["_quoted":protected]=>
          bool(false)
        }

        ["name"]=>
        object(Doctrine\DBAL\Schema\Column)#723 (16) {
          ["_type":protected]=>
          object(Doctrine\DBAL\Types\StringType)#466 (0) {
          }
          ["_length":protected]=>
          int(255)
          ["_precision":protected]=>
          int(10)
          ["_scale":protected]=>
          int(0)
          ["_unsigned":protected]=>
          bool(false)
          ["_fixed":protected]=>
          bool(false)
          ["_notnull":protected]=>
          bool(true)
          ["_default":protected]=>
          NULL
          ["_autoincrement":protected]=>
          bool(false)
          ["_platformOptions":protected]=>
          array(2) {
            ["charset"]=>
            string(4) "utf8"
            ["collation"]=>
            string(15) "utf8_general_ci"
          }
          ["_columnDefinition":protected]=>
          NULL
          ["_comment":protected]=>
          NULL
          ["_customSchemaOptions":protected]=>
          array(0) {
          }
          ["_name":protected]=>
          string(4) "name"
          ["_namespace":protected]=>
          NULL
          ["_quoted":protected]=>
          bool(false)
        }

        ["short"]=>
        object(Doctrine\DBAL\Schema\Column)#728 (16) {
          ["_type":protected]=>
          object(Doctrine\DBAL\Types\StringType)#466 (0) {
          }
          ["_length":protected]=>
          int(50)
          ["_precision":protected]=>
          int(10)
          ["_scale":protected]=>
          int(0)
          ["_unsigned":protected]=>
          bool(false)
          ["_fixed":protected]=>
          bool(false)
          ["_notnull":protected]=>
          bool(true)
          ["_default":protected]=>
          NULL
          ["_autoincrement":protected]=>
          bool(false)
          ["_platformOptions":protected]=>
          array(2) {
            ["charset"]=>
            string(4) "utf8"
            ["collation"]=>
            string(15) "utf8_general_ci"
          }
          ["_columnDefinition":protected]=>
          NULL
          ["_comment":protected]=>
          NULL
          ["_customSchemaOptions":protected]=>
          array(0) {
          }
          ["_name":protected]=>
          string(5) "short"
          ["_namespace":protected]=>
          NULL
          ["_quoted":protected]=>
          bool(false)
        }


#########
### TO ###
#########
object(Doctrine\DBAL\Schema\Schema)#6572 (7) {
  ["namespaces":"Doctrine\DBAL\Schema\Schema":private]=>
  array(0) {
  }
  ["_tables":protected]=>
  array(63) {
    ["app.table"]=>
    object(Doctrine\DBAL\Schema\Table)#6568 (11) {
      ["_columns":protected]=>
      array(6) {

        ["description"]=>
        object(Doctrine\DBAL\Schema\Column)#6567 (16) {
          ["_type":protected]=>
          object(Doctrine\DBAL\Types\TextType)#760 (0) {
          }
          ["_length":protected]=>
          NULL
          ["_precision":protected]=>
          int(10)
          ["_scale":protected]=>
          int(0)
          ["_unsigned":protected]=>
          bool(false)
          ["_fixed":protected]=>
          bool(false)
          ["_notnull":protected]=>
          bool(true)
          ["_default":protected]=>
          NULL
          ["_autoincrement":protected]=>
          bool(false)
          ["_platformOptions":protected]=>
          array(1) {
            ["version"]=>
            bool(false)
          }
          ["_columnDefinition":protected]=>
          NULL
          ["_comment":protected]=>
          NULL
          ["_customSchemaOptions":protected]=>
          array(0) {
          }
          ["_name":protected]=>
          string(11) "description"
          ["_namespace":protected]=>
          NULL
          ["_quoted":protected]=>
          bool(false)
        }

        ["name"]=>
        object(Doctrine\DBAL\Schema\Column)#6566 (16) {
          ["_type":protected]=>
          object(Doctrine\DBAL\Types\StringType)#466 (0) {
          }
          ["_length":protected]=>
          int(255)
          ["_precision":protected]=>
          int(10)
          ["_scale":protected]=>
          int(0)
          ["_unsigned":protected]=>
          bool(false)
          ["_fixed":protected]=>
          bool(false)
          ["_notnull":protected]=>
          bool(true)
          ["_default":protected]=>
          NULL
          ["_autoincrement":protected]=>
          bool(false)
          ["_platformOptions":protected]=>
          array(1) {
            ["version"]=>
            bool(false)
          }
          ["_columnDefinition":protected]=>
          NULL
          ["_comment":protected]=>
          NULL
          ["_customSchemaOptions":protected]=>
          array(0) {
          }
          ["_name":protected]=>
          string(4) "name"
          ["_namespace":protected]=>
          NULL
          ["_quoted":protected]=>
          bool(false)
        }

        ["short"]=>
        object(Doctrine\DBAL\Schema\Column)#6565 (16) {
          ["_type":protected]=>
          object(Doctrine\DBAL\Types\StringType)#466 (0) {
          }
          ["_length":protected]=>
          int(50)
          ["_precision":protected]=>
          int(10)
          ["_scale":protected]=>
          int(0)
          ["_unsigned":protected]=>
          bool(false)
          ["_fixed":protected]=>
          bool(false)
          ["_notnull":protected]=>
          bool(true)
          ["_default":protected]=>
          NULL
          ["_autoincrement":protected]=>
          bool(false)
          ["_platformOptions":protected]=>
          array(1) {
            ["version"]=>
            bool(false)
          }
          ["_columnDefinition":protected]=>
          NULL
          ["_comment":protected]=>
          NULL
          ["_customSchemaOptions":protected]=>
          array(0) {
          }
          ["_name":protected]=>
          string(5) "short"
          ["_namespace":protected]=>
          NULL
          ["_quoted":protected]=>
          bool(false)
        }


########################
### MYSQL DEFINITION ###
########################
mysql> desc table;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int          | NO   | PRI | NULL    | auto_increment |
| name        | varchar(255) | NO   |     | NULL    |                |
| short       | varchar(50)  | NO   |     | NULL    |                |
| description | longtext     | NO   |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+



########################
### ENTITY DEFINITION ###
########################
/**
 * @ORM\Column(name="description", type="text", nullable=false)
 */
private string $description;

/**
 * @ORM\Column(name="name", type="string", length=255, nullable=false)
 */
private string $name;

/**
 * @ORM\Column(name="short", type="string", length=50, nullable=false)
 */
private string $short;



########################
### GENERATED down() ###
########################
this->addSql('ALTER TABLE table CHANGE description description LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE short short VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
```

Here are the differences I noticed:

`$this->createFromSchema();`:
- description
  - length: `int(0)`
  - _platformOptions: `[charset => utf8, collation => utf8_general_ci]`
- name
  - _platformOptions: `[charset => utf8, collation => utf8_general_ci]`
- short 
  - _platformOptions: `[charset => utf8, collation => utf8_general_ci]`


`$this->createToSchema();`:
- description
  - length: `NULL`
  - _platformOptions: `[version => false]`
- name
  - _platformOptions: `[version => false]`
- short 
  - _platformOptions: `[version => false]`

I will keep trying to dig into it, but I'm just slowly fumbling around---perhaps the above will be enough for someone familiar with the codebase to have an "aha!" moment...

**Comment by greg0ire** [comment]
I think you will get something more detailed with `SHOW CREATE TABLE table` than with `desc table`.
The dumps you provided seem to explain pretty well the `down()` method, what I don't get is why `up()` is empty :thinking:

**Comment by greg0ire** [comment]
Also, I just debugged @natewiebe13 's project, and in that project, `$toSchema` has the `collation` platform option.

What happens to that variable when you use

```yaml
    default_table_options:
      collation: utf8_general_ci
```

? I would expect this might make `$toSchema` consistent with `$fromSchema`

**Comment by greg0ire** [comment]
@arderyp it would also be great to confirm you go through this method when generating `up()` and when generating `down()`: https://github.com/doctrine/dbal/blob/7ac309579ac0a14e525144229c8feebf79e8d1e7/src/Platforms/MySQL/Comparator.php#L34-L47

**Comment by floviolleau** [comment]
Hi,

I'm jumping into the discussion and I have similar issue

I updated to latest and I still have the issue.
If I don't configure anything in doctrine.yml, I still have a migration generated in down() function. If I configure something, still the junk down generated. Whatever values I set for charset and collation... In my DB I have a mix of utf8 and utf8mb4 tables. Most of the tables are in utf8. Only few are in utf8mb4 (coming from vendors).

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                server_version: 5.7
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            tracabilite:
                connection: tracabilite
```

```bash
Restricting packages listed in "symfony/symfony" to "5.4.*"
Updating dependencies
Lock file operations: 0 installs, 9 updates, 0 removals
  - Upgrading doctrine/dbal (3.3.0 => 3.3.2)
  - Upgrading doctrine/doctrine-bundle (2.5.5 => 2.5.6)
  - Upgrading phar-io/version (3.1.0 => 3.1.1)
  - Upgrading psalm/plugin-symfony (v3.1.2 => v3.1.3)
  - Upgrading react/promise (v2.8.0 => v2.9.0)
  - Upgrading sebastian/global-state (5.0.3 => 5.0.5)
  - Upgrading symfony/webpack-encore-bundle (v1.13.2 => v1.14.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 10 updates, 0 removals
  - Downloading composer/package-versions-deprecated (1.11.99.1)
  - Downloading doctrine/dbal (3.3.2)
  - Downloading doctrine/doctrine-bundle (2.5.6)
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Downgrading composer/package-versions-deprecated (1.11.99.5 => 1.11.99.1): Extracting archive
  - Upgrading doctrine/dbal (3.3.0 => 3.3.2): Extracting archive
  - Upgrading doctrine/doctrine-bundle (2.5.5 => 2.5.6): Extracting archive
  - Upgrading react/promise (v2.8.0 => v2.9.0): Extracting archive
  - Upgrading sebastian/global-state (5.0.3 => 5.0.5): Extracting archive
  - Upgrading phar-io/version (3.1.0 => 3.1.1): Extracting archive
  - Upgrading psalm/plugin-symfony (v3.1.2 => v3.1.3): Extracting archive
  - Upgrading symfony/webpack-encore-bundle (v1.13.2 => v1.14.0): Extracting archive
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
```

I'm not enough experienced in this bundle to be able to make any suggestions, but I can do tests on a big DB.

Thanks!

**Comment by greg0ire** [comment]
@floviolleau maybe you can do some step by step debugging here: https://github.com/doctrine/migrations/blob/e7df670aa9565b435ffec636cebdb4d0a1987f10/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L103-L123

It would be great to figure out why there is this asymmetry between `up()` and `down()`. It would also be interesting to put a breakpoint here to figure out what is going on: https://github.com/doctrine/dbal/blob/7ac309579ac0a14e525144229c8feebf79e8d1e7/src/Platforms/MySQL/Comparator.php#L34-L47

**Comment by floviolleau** [comment]
<details>
  <summary>In vendor/doctrine/dbal/src/Platforms/MySQL/Comparator.php line 47 dump $fromTable</summary>
  
```
^ Doctrine\DBAL\Schema\Table^ {#212
  #_columns: array:3 [
    "version" => Doctrine\DBAL\Schema\Column^ {#210
      #_type: Doctrine\DBAL\Types\StringType^ {#265}
      #_length: 191
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: true
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "version"
      #_namespace: null
      #_quoted: false
    }
    "executed_at" => Doctrine\DBAL\Schema\Column^ {#213
      #_type: Doctrine\DBAL\Types\DateTimeType^ {#277}
      #_length: 0
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "executed_at"
      #_namespace: null
      #_quoted: false
    }
    "execution_time" => Doctrine\DBAL\Schema\Column^ {#209
      #_type: Doctrine\DBAL\Types\IntegerType^ {#270}
      #_length: null
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "execution_time"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_indexes: array:1 [
    "primary" => Doctrine\DBAL\Schema\Index^ {#208
      #_columns: array:1 [
        "version" => Doctrine\DBAL\Schema\Identifier^ {#223
          #_name: "version"
          #_namespace: null
          #_quoted: false
        }
      ]
      #_isUnique: true
      #_isPrimary: true
      #_flags: []
      -options: array:1 [
        "lengths" => array:1 [
          0 => null
        ]
      ]
      #_name: "PRIMARY"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_primaryKeyName: "primary"
  #uniqueConstraints: []
  #_fkConstraints: []
  #_options: array:5 [
    "create_options" => []
    "engine" => "InnoDB"
    "collation" => "utf8_unicode_ci"
    "charset" => "utf8"
    "comment" => ""
  ]
  #_schemaConfig: null
  -implicitIndexes: []
  #_name: "doctrine_migration_versions"
  #_namespace: null
  #_quoted: false
}
^ Doctrine\DBAL\Schema\Table^ {#1294
  #_columns: array:3 [
    "version" => Doctrine\DBAL\Schema\Column^ {#1295
      #_type: Doctrine\DBAL\Types\StringType^ {#265}
      #_length: 191
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: true
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "version"
      #_namespace: null
      #_quoted: false
    }
    "executed_at" => Doctrine\DBAL\Schema\Column^ {#1296
      #_type: Doctrine\DBAL\Types\DateTimeType^ {#277}
      #_length: 0
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "executed_at"
      #_namespace: null
      #_quoted: false
    }
    "execution_time" => Doctrine\DBAL\Schema\Column^ {#1292
      #_type: Doctrine\DBAL\Types\IntegerType^ {#270}
      #_length: null
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "execution_time"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_indexes: array:1 [
    "primary" => Doctrine\DBAL\Schema\Index^ {#1291
      #_columns: array:1 [
        "version" => Doctrine\DBAL\Schema\Identifier^ {#1302
          #_name: "version"
          #_namespace: null
          #_quoted: false
        }
      ]
      #_isUnique: true
      #_isPrimary: true
      #_flags: []
      -options: array:1 [
        "lengths" => array:1 [
          0 => null
        ]
      ]
      #_name: "PRIMARY"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_primaryKeyName: "primary"
  #uniqueConstraints: []
  #_fkConstraints: []
  #_options: array:5 [
    "create_options" => []
    "engine" => "InnoDB"
    "collation" => "utf8_unicode_ci"
    "charset" => "utf8"
    "comment" => ""
  ]
  #_schemaConfig: null
  -implicitIndexes: []
  #_name: "doctrine_migration_versions"
  #_namespace: null
  #_quoted: false
}
```
</details>

<details>
  <summary>In vendor/doctrine/dbal/src/Platforms/MySQL/Comparator.php line 47 dump $toTable</summary>
  
```
^ Doctrine\DBAL\Schema\Table^ {#207
  #_columns: array:3 [
    "version" => Doctrine\DBAL\Schema\Column^ {#206
      #_type: Doctrine\DBAL\Types\StringType^ {#265}
      #_length: 191
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: true
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "version"
      #_namespace: null
      #_quoted: false
    }
    "executed_at" => Doctrine\DBAL\Schema\Column^ {#205
      #_type: Doctrine\DBAL\Types\DateTimeType^ {#277}
      #_length: null
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "executed_at"
      #_namespace: null
      #_quoted: false
    }
    "execution_time" => Doctrine\DBAL\Schema\Column^ {#204
      #_type: Doctrine\DBAL\Types\IntegerType^ {#270}
      #_length: null
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "execution_time"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_indexes: array:1 [
    "primary" => Doctrine\DBAL\Schema\Index^ {#176
      #_columns: array:1 [
        "version" => Doctrine\DBAL\Schema\Identifier^ {#228
          #_name: "version"
          #_namespace: null
          #_quoted: false
        }
      ]
      #_isUnique: true
      #_isPrimary: true
      #_flags: []
      -options: []
      #_name: "primary"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_primaryKeyName: "primary"
  #uniqueConstraints: []
  #_fkConstraints: []
  #_options: array:1 [
    "create_options" => []
  ]
  #_schemaConfig: null
  -implicitIndexes: []
  #_name: "doctrine_migration_versions"
  #_namespace: null
  #_quoted: false
}
^ Doctrine\DBAL\Schema\Table^ {#1290
  #_columns: array:3 [
    "version" => Doctrine\DBAL\Schema\Column^ {#1289
      #_type: Doctrine\DBAL\Types\StringType^ {#265}
      #_length: 191
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: true
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "version"
      #_namespace: null
      #_quoted: false
    }
    "executed_at" => Doctrine\DBAL\Schema\Column^ {#1288
      #_type: Doctrine\DBAL\Types\DateTimeType^ {#277}
      #_length: null
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "executed_at"
      #_namespace: null
      #_quoted: false
    }
    "execution_time" => Doctrine\DBAL\Schema\Column^ {#1287
      #_type: Doctrine\DBAL\Types\IntegerType^ {#270}
      #_length: null
      #_precision: 10
      #_scale: 0
      #_unsigned: false
      #_fixed: false
      #_notnull: false
      #_default: null
      #_autoincrement: false
      #_platformOptions: []
      #_columnDefinition: null
      #_comment: null
      #_customSchemaOptions: []
      #_name: "execution_time"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_indexes: array:1 [
    "primary" => Doctrine\DBAL\Schema\Index^ {#1286
      #_columns: array:1 [
        "version" => Doctrine\DBAL\Schema\Identifier^ {#1310
          #_name: "version"
          #_namespace: null
          #_quoted: false
        }
      ]
      #_isUnique: true
      #_isPrimary: true
      #_flags: []
      -options: []
      #_name: "primary"
      #_namespace: null
      #_quoted: false
    }
  ]
  #_primaryKeyName: "primary"
  #uniqueConstraints: []
  #_fkConstraints: []
  #_options: array:1 [
    "create_options" => []
  ]
  #_schemaConfig: null
  -implicitIndexes: []
  #_name: "doctrine_migration_versions"
  #_namespace: null
  #_quoted: false
}
```
</details>

<details>
  <summary>In vendor/doctrine/dbal/src/Platforms/MySQL/Comparator.php line 47 dump $defaults</summary>

```
^ array:2 [
  "collation" => "utf8_unicode_ci"
  "charset" => "utf8"
]
^ array:2 [
  "collation" => "utf8_unicode_ci"
  "charset" => "utf8"
]
```
</details>

Dump $upSql l.106
``` 
^ array:1 [
  0 => "DROP TABLE doctrine_migration_versions"
]
```
=> in migration files, up is empty

Dump $downSql l.117 => big output of almost all my tables. Extract:
```php
[...]
$this->addSql('ALTER TABLE client CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, CHANGE logo logo VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE img_home img_home VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE template_cq template_cq VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE code_gc code_gc VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE default_folders default_folders LONGTEXT CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE screensaver_path screensaver_path VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE intent_token intent_token VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE type_app type_app VARCHAR(255) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_unicode_ci`, CHANGE libelle_produit libelle_produit VARCHAR(255) CHARACTER SET utf8 DEFAULT \'Produit\' NOT NULL COLLATE `utf8_unicode_ci`');
[...]
```

<details>
  <summary>In vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/DiffGenerator.php l.113 dump $toSchema</summary>

```
^ Doctrine\DBAL\Schema\Schema^ {#15674
  -namespaces: []
  #_tables: array:113 [
    "event" => Doctrine\DBAL\Schema\Table^ {#15675
      #_columns: array:25 [
        "id" => Doctrine\DBAL\Schema\Column^ {#15676 …16}
        "unique_id" => Doctrine\DBAL\Schema\Column^ {#15672 …16}
        "alerte_device" => Doctrine\DBAL\Schema\Column^ {#15671 …16}
        "timestamp" => Doctrine\DBAL\Schema\Column^ {#15670 …16}
        "event_code" => Doctrine\DBAL\Schema\Column^ {#15669 …16}
        "action_code" => Doctrine\DBAL\Schema\Column^ {#15668 …16}
        "badge" => Doctrine\DBAL\Schema\Column^ {#15667 …16}
        "complement" => Doctrine\DBAL\Schema\Column^ {#15666 …16}
        "error" => Doctrine\DBAL\Schema\Column^ {#15665 …16}
        "external_state" => Doctrine\DBAL\Schema\Column^ {#15664 …16}
        "ack_error" => Doctrine\DBAL\Schema\Column^ {#15663 …16}
        "acked_at" => Doctrine\DBAL\Schema\Column^ {#15662 …16}
        "internal_state" => Doctrine\DBAL\Schema\Column^ {#15661 …16}
        "dispatch_error" => Doctrine\DBAL\Schema\Column^ {#15660 …16}
        "dispatch_at" => Doctrine\DBAL\Schema\Column^ {#15642 …16}
        "ticket_id" => Doctrine\DBAL\Schema\Column^ {#15658 …16}
        "releve_id" => Doctrine\DBAL\Schema\Column^ {#15678 …16}
        "battery_level" => Doctrine\DBAL\Schema\Column^ {#15679 …16}
        "created_at" => Doctrine\DBAL\Schema\Column^ {#15681 …16}
        "updated_at" => Doctrine\DBAL\Schema\Column^ {#15682 …16}
        "site_id" => Doctrine\DBAL\Schema\Column^ {#15683 …16}
        "local_id" => Doctrine\DBAL\Schema\Column^ {#15690 …16}
        "satisfaction_id" => Doctrine\DBAL\Schema\Column^ {#15697 …16}
        "created_by" => Doctrine\DBAL\Schema\Column^ {#15704 …16}
        "updated_by" => Doctrine\DBAL\Schema\Column^ {#15711 …16}
      ]
      #_indexes: array:6 [
        "idx_7d51558ef6bd1646" => Doctrine\DBAL\Schema\Index^ {#15688 …8}
        "idx_7d51558e5d5a2101" => Doctrine\DBAL\Schema\Index^ {#15695 …8}
        "uniq_7d51558ede9439b8" => Doctrine\DBAL\Schema\Index^ {#15698 …8}
        "idx_7d51558ede12ab56" => Doctrine\DBAL\Schema\Index^ {#15709 …8}
        "idx_7d51558e16fe72e1" => Doctrine\DBAL\Schema\Index^ {#15716 …8}
        "primary" => Doctrine\DBAL\Schema\Index^ {#15718 …8}
      ]
      #_primaryKeyName: "primary"
      #uniqueConstraints: []
      #_fkConstraints: array:5 [
        "fk_7d51558ef6bd1646" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#15684 …8}
        "fk_7d51558e5d5a2101" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#15691 …8}
        "fk_7d51558ede9439b8" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#15700 …8}
        "fk_7d51558ede12ab56" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#15705 …8}
        "fk_7d51558e16fe72e1" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#15712 …8}
      ]
      #_options: array:3 [
        "create_options" => []
        "collation" => "utf8mb4_unicode_ci"
        "charset" => "utf8mb4"
      

[...]
```
</details>

<details>
  <summary>In vendor/doctrine/migrations/lib/Doctrine/Migrations/Generator/DiffGenerator.php l.113 dump $fromSchema</summary>

```
^ Doctrine\DBAL\Schema\Schema^ {#6727
  -namespaces: []
  #_tables: array:114 [
    "event" => Doctrine\DBAL\Schema\Table^ {#222
      #_columns: array:25 [
        "id" => Doctrine\DBAL\Schema\Column^ {#210 …16}
        "unique_id" => Doctrine\DBAL\Schema\Column^ {#199 …16}
        "alerte_device" => Doctrine\DBAL\Schema\Column^ {#209 …16}
        "timestamp" => Doctrine\DBAL\Schema\Column^ {#240 …16}
        "event_code" => Doctrine\DBAL\Schema\Column^ {#234 …16}
        "badge" => Doctrine\DBAL\Schema\Column^ {#233 …16}
        "complement" => Doctrine\DBAL\Schema\Column^ {#239 …16}
        "error" => Doctrine\DBAL\Schema\Column^ {#238 …16}
        "created_at" => Doctrine\DBAL\Schema\Column^ {#236 …16}
        "updated_at" => Doctrine\DBAL\Schema\Column^ {#195 …16}
        "external_state" => Doctrine\DBAL\Schema\Column^ {#202 …16}
        "action_code" => Doctrine\DBAL\Schema\Column^ {#189 …16}
        "internal_state" => Doctrine\DBAL\Schema\Column^ {#178 …16}
        "ack_error" => Doctrine\DBAL\Schema\Column^ {#179 …16}
        "acked_at" => Doctrine\DBAL\Schema\Column^ {#180 …16}
        "dispatch_error" => Doctrine\DBAL\Schema\Column^ {#182 …16}
        "dispatch_at" => Doctrine\DBAL\Schema\Column^ {#183 …16}
        "ticket_id" => Doctrine\DBAL\Schema\Column^ {#208 …16}
        "releve_id" => Doctrine\DBAL\Schema\Column^ {#212 …16}
        "battery_level" => Doctrine\DBAL\Schema\Column^ {#206 …16}
        "site_id" => Doctrine\DBAL\Schema\Column^ {#205 …16}
        "satisfaction_id" => Doctrine\DBAL\Schema\Column^ {#204 …16}
        "local_id" => Doctrine\DBAL\Schema\Column^ {#176 …16}
        "created_by" => Doctrine\DBAL\Schema\Column^ {#207 …16}
        "updated_by" => Doctrine\DBAL\Schema\Column^ {#216 …16}
      ]
      #_indexes: array:6 [
        "idx_7d51558e16fe72e1" => Doctrine\DBAL\Schema\Index^ {#2770 …8}
        "uniq_7d51558ede9439b8" => Doctrine\DBAL\Schema\Index^ {#2765 …8}
        "idx_7d51558e5d5a2101" => Doctrine\DBAL\Schema\Index^ {#2767 …8}
        "primary" => Doctrine\DBAL\Schema\Index^ {#228 …8}
        "idx_7d51558ef6bd1646" => Doctrine\DBAL\Schema\Index^ {#219 …8}
        "idx_7d51558ede12ab56" => Doctrine\DBAL\Schema\Index^ {#191 …8}
      ]
      #_primaryKeyName: "primary"
      #uniqueConstraints: []
      #_fkConstraints: array:5 [
        "fk_7d51558ede9439b8" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#217 …8}
        "fk_7d51558e16fe72e1" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#291 …8}
        "fk_7d51558ede12ab56" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#293 …8}
        "fk_7d51558ef6bd1646" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#286 …8}
        "fk_7d51558e5d5a2101" => Doctrine\DBAL\Schema\ForeignKeyConstraint^ {#197 …8}
      ]
      #_options: array:6 [
        "create_options" => []
        "engine" => "InnoDB"
        "collation" => "utf8_unicode_ci"
        "charset" => "utf8"
        "autoincrement" => "390317"
        "comment" => ""
      ]
      #_schemaConfig: Doctrine\DBAL\Schema\SchemaConfig^ {#6766
        #hasExplicitForeignKeyIndexes: false
        #maxIdentifierLength: 63
        #name: "toto"
        #defaultTableOptions: array:2 [
          "collation" => "utf8mb4_unicode_ci"
          "charset" => "utf8mb4"
        ]
      }

[...]
```
</details>

@greg0ire what do you want to see exactly?

**Comment by greg0ire** [comment]
I notice that there is a diff in options:

`toSchema`:

```
      #_options: array:3 [
        "create_options" => []
        "collation" => "utf8mb4_unicode_ci"
        "charset" => "utf8mb4"
```

`fromSchema`:

```
      #_options: array:6 [
        "create_options" => []
        "engine" => "InnoDB"
        "collation" => "utf8_unicode_ci"
        "charset" => "utf8"
        "autoincrement" => "390317"
        "comment" => ""
      ]
```

Can you show use the output of `SHOW CREATE TABLE event`?
Assuming you don't really care about what collation you are using (since you tried not specifying anything), I'd say that by default, `utf8mb4_unicode_ci` should be used on every table, right? SInce there is this line: https://github.com/doctrine/DoctrineBundle/blob/f1423b2a640b6ac545b6e0c02575427a4dc1e9dc/ConnectionFactory.php#L95

I think the fact you have a mix of both collations is already a bug, and I think the second bug might be that you should have an `up()` method that migrates all of your schema to `utf8mb4_unicode_ci`, but somehow does not.

What I'd like to see is something that explains the big diff. That difference in options might be it.

Also, I think the the asymmetry can be explained by this lines: https://github.com/doctrine/dbal/blob/7ac309579ac0a14e525144229c8feebf79e8d1e7/src/Platforms/MySQL/Comparator.php#L34-L37

In the case of `up()` `fromSchema` is introspected from the database, while in the case of `down()`, it's built from settings and metadata.

UPD: BTW, I'm not well versed in encoding, but a cursory web search shows that you should really not be using `utf8` at all: https://stackoverflow.com/questions/30074492/what-is-the-difference-between-utf8mb4-and-utf8-charsets-in-mysql

**Comment by floviolleau** [comment]
Thanks a lot for investing it! I do appreciate it <3

Here is the sql query
```sql
mysql> SHOW CREATE TABLE event;
+---------------+----------------------------------------------------------------------------------------------------------+
| Table         | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+---------------+----------------------------------------------------------------------------------------------------------+
| event | CREATE TABLE `event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unique_id` int(11) NOT NULL,
  `alerte_device` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `timestamp` datetime NOT NULL,
  `event_code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `badge` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `complement` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `error` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `external_state` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `action_code` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `internal_state` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ack_error` longtext COLLATE utf8_unicode_ci,
  `acked_at` datetime DEFAULT NULL,
  `dispatch_error` longtext COLLATE utf8_unicode_ci,
  `dispatch_at` datetime DEFAULT NULL,
  `ticket_id` int(11) DEFAULT NULL,
  `releve_id` int(11) DEFAULT NULL,
  `battery_level` int(11) DEFAULT NULL,
  `site_id` int(11) DEFAULT NULL,
  `satisfaction_id` int(11) DEFAULT NULL,
  `local_id` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_7D51558EDE9439B8` (`satisfaction_id`),
  KEY `IDX_7D51558EF6BD1646` (`site_id`),
  KEY `IDX_7D51558E5D5A2101` (`local_id`),
  KEY `IDX_7D51558EDE12AB56` (`created_by`),
  KEY `IDX_7D51558E16FE72E1` (`updated_by`),
  CONSTRAINT `FK_7D51558E16FE72E1` FOREIGN KEY (`updated_by`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_7D51558E5D5A2101` FOREIGN KEY (`local_id`) REFERENCES `local` (`id`),
  CONSTRAINT `FK_7D51558EDE12AB56` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_7D51558EDE9439B8` FOREIGN KEY (`satisfaction_id`) REFERENCES `satisfaction` (`id`) ON DELETE SET NULL,
  CONSTRAINT `FK_7D51558EF6BD1646` FOREIGN KEY (`site_id`) REFERENCES `site` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=390317 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+---------------+----------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

This is my understanding as well. If I specify charset utf-8 a collation utf-8, I have a diff generated only on small tables that are currently in utf8mb4

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                server_version: 5.7
                charset: utf8
                default_table_options:
                    charset: utf8
                    collation: utf8_unicode_ci
```

Small output in down() with only lines asking for utf8mb4 and utf8mb4_unicode_ci
```php
[...]

        $this->addSql('ALTER TABLE async_job CHANGE state state VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE message message LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE error error LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`');

[...]
```

At the beginning of this project (several years ago), nothing was specified in doctrine config and it was by default utf8 utf8_unicode_ci. Now the default is utf8mb4 and utf8mb4_unicode_ci and because nothing was still specified in doctrine config, new tables / updated fields are in utf8mb4. So it could explain why I have a mix of utf8 and utf8mb4 tables.

Maybe I should create a migration to move all tables from utf8 to utf8mb4 and utf8_unicode_ci to utf8mb4_unicode_ci to fix the problem?

**Comment by dmaicher** [comment]
I'm also having the same issues with empty `up()` and lots of queries in `down()` even when using latest DoctrineBundle + latest DBAL versions. I also use `charset: utf8` and `collation: utf8_unicode_ci` :thinking: 

Thanks for investigating @greg0ire @floviolleau . Let me know if I should also check or test something on my end

**Comment by greg0ire** [comment]
@dmaicher out of curiosity, what made you pick `utf8` over `utf8mb4`? From what I read, one should stay away from `utf8`.

Also, FYI, I have created this failing test that I think shows an issue with DBAL: https://github.com/doctrine/dbal/pull/5275

**Comment by dmaicher** [comment]
> @dmaicher out of curiosity, what made you pick `utf8` over `utf8mb4`? From what I read, one should stay away from `utf8`.
> 
> Also, FYI, I have created this failing test that I think shows an issue with DBAL: [doctrine/dbal#5275](https://github.com/doctrine/dbal/pull/5275)

This project was created 11 years ago and we never updated the charset :man_shrugging: :smile:

**Comment by greg0ire** [comment]
@dmaicher in your case, what collation does the `down()` method mention?

**Comment by arderyp** [comment]
```
table | CREATE TABLE `table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `short` varchar(50) NOT NULL,
  `description` longtext NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb3 COMMENT='List of applications in CEE''s system.' 
```

**Comment by arderyp** [comment]
@greg0ire here is the create 

```
table | CREATE TABLE `table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `short` varchar(50) NOT NULL,
  `description` longtext NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb3 COMMENT='table' 
```

Using

```
default_table_options:
      collation: utf8_general_ci
```

created the same results.

**Comment by greg0ire** [comment]
Ok so it seems you too are using the deprecated `utf8mb3`… :thinking: interesting!

**Comment by arderyp** [comment]
@greg0ire When dumping `$defaults` [here](https://github.com/doctrine/dbal/blob/7ac309579ac0a14e525144229c8feebf79e8d1e7/src/Platforms/MySQL/Comparator.php#L34-L47)

`$comparator->compareSchemas($fromSchema, $toSchema)` creates:

```
array(2) {
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "utf8"
}

```

`$comparator->compareSchemas($toSchema, $fromSchema)` creates:

```
array(2) {
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "UTF8"
}
```

Before the code enters the up/down schema generation, it falls into the linked block and dump the following twice:

```
array(2) {
  ["collation"]=>
  string(15) "utf8_unicode_ci"
  ["charset"]=>
  string(4) "utf8"
}
```

**Comment by arderyp** [comment]
as for why people are uding "UTF8" or "utf8", I probably am because of symfony documentation: https://symfony.com/doc/current/reference/configuration/doctrine.html

**Comment by arderyp** [comment]
@greg0ire I am happy to dig more into the up/down schema generation.  Do you have any instinct as to which one may be correct in my case?  I'm thinking if we know which one is correct, I should focus on digging into the other, but happy to follow your lead wherever.

**Comment by dmaicher** [comment]
> @dmaicher in your case, what collation does the `down()` method mention?

@greg0ire So I'm using this config

```yaml
charset: utf8
default_table_options:
    collation: utf8_general_ci
```

And I have an empty `up()` and lots of those inside `down()`

```
ALTER TABLE address CHANGE street street LONGTEXT DEFAULT NULL COLLATE `utf8_unicode_ci`
``` 

So somehow it seems to be a mismatch between `utf8_general_ci` and `utf8_unicode_ci`?

**Comment by greg0ire** [comment]
:thinking: from what I read here, it is recommended to use `_unicode_` over `_general_`.

> So somehow it seems to be a mismatch between utf8_general_ci and utf8_unicode_ci?

I would expect `up()` to mention what is defined in your config, but for `down()`, I would expect it to mention whatever is introspected. If you use `SHOW CREATE TABLE address`, what do you get?

**Comment by greg0ire** [comment]
> as for why people are uding "UTF8" or "utf8", I probably am because of symfony documentation: https://symfony.com/doc/current/reference/configuration/doctrine.html

Thanks for this, I think I'm going to open a PR to fix this :sweat_smile: Although I prefer Postgres, and am not a specialist of MySQL, a quick web search shows that this is not a sensible default.

**Comment by greg0ire** [comment]
> Thanks for this, I think I'm going to open a PR to fix this sweat_smile

But before that, I need to figure out several things:
- what are the recommended settings when using MySQL for `charset` and `collation`?
- what does DBAL do by default, when you don't specify those? Apparently it picks `utf8`, and then sticks `_unicode_ci` to that to obtain the `collation`.
- what does `DoctrineBundle` do when you don't specify those in the configuration?

UPD: Created
-  https://github.com/doctrine/dbal/pull/5277
- https://github.com/doctrine/dbal/pull/5278
- https://github.com/doctrine/DoctrineBundle/pull/1479
- https://github.com/symfony/recipes/pull/1059
- https://github.com/symfony/symfony-docs/pull/16515

**Comment by arderyp** [comment]
Thanks for creating those issues, and if UTF8 does indeed seem like a wrong default, then opening an issue with Symfony Docs would be helpful.

In the mean time, how explicitly would you change the following for it to be more sensible and explicit:

```
doctrine:
  dbal:
    driver: pdo_mysql
    charset: ???
    default_table_options:
      collation: ???
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
```

Do any other keyed elements need to be added?  `server_version`?

Once we are clear on the recommended default config for utf8-style configuration, do you think I should focus more on the up or down schema generation for further debugging? Should `up()` be generating migrations for these fields:

```
table | CREATE TABLE `table` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `short` varchar(50) NOT NULL,
  `description` longtext NOT NULL,
  `created` datetime NOT NULL,
  `modified` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb3 COMMENT='table' 
```

My guess is "yes" given the `CHARSET=utf8mb3` part, and you suggest that's not the advisible charset.  

Based on the comments here and my debugging, it sounds like the `up()` function is mapping `UTF8` charset configuration to `utf8mb3` (`_platformOptions: [charset => utf8, collation => utf8_general_ci]`) causing the `up()` method to see the schema as in sync since my tables are `utf8mb3`, while the `down()` function maps the `UTF8` configuration to some other value or perhaps nothing at all (`_platformOptions: [version => false]`). `_platformOptions` examples come from my earlier [comment](https://github.com/doctrine/DoctrineBundle/pull/1471#issuecomment-1039858431).

**Comment by greg0ire** [comment]
For the moment this is _my_ recommendation

```yaml
doctrine:
  dbal:
    driver: pdo_mysql
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collation: utf8mb4_unicode_ci # or even utf8mb4_0900_ai_ci if using MySQL 8
    host: '%env(DATABASE_HOST)%'
    port: '%env(DATABASE_PORT)%'
    dbname: '%env(DATABASE_NAME)%'
    user: '%env(DATABASE_USER)%'
    password: '%env(DATABASE_PASSWORD)%'
```

Then you can try inserting emojis in your table :slightly_smiling_face: 
From what I understand, `up()` is not generated because platform-aware comparison only works at the column level for now, and not at the table level: https://github.com/doctrine/dbal/issues/4945

**Comment by greg0ire** [comment]
@arderyp until the DBAL is able to do the charset/collation migration, maybe use `utf8mb3` everywhere? Might make the `down()` diff go away? Also, I'm wondering if that issue is specific to platform-aware comparison. If yes, you might be able to downgrade the DBAL to 3.3.0, use `utf8mb4` everywhere, migrate your tables, then upgrade back to `3.3.2`

**Comment by arderyp** [comment]
I am comparing `$fromTable->getOptions` and `$toTable->getOptions()` [here](https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/MySQL/Comparator.php#L32) for the table I've been using in my examples, and it's clear they are just not parsing the same options:

```
# FROM
array(6) {
  ["create_options"]=>
  array(0) {
  }
  ["engine"]=>
  string(6) "InnoDB"
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "utf8"
  ["autoincrement"]=>
  string(2) "20"
  ["comment"]=>
  string(37) "List of applications in CEE's system."
}

# TO
array(3) {
  ["create_options"]=>
  array(0) {
  }
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "UTF8"
}
```

setting `charset` to `utf8mb3` in my config throws an error about unrecognized charset.  Are you suggesting I migrate the tables manually to `utf8mb3` and that this may resolve errors with the `charset: UTF8` config?

**Comment by arderyp** [comment]
I am comparing `$fromTable->getOptions` and `$toTable->getOptions()` [here](https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/MySQL/Comparator.php#L32) for the table I've been using in my examples, and it's clear they are just not parsing the same options:

```
# FROM
array(6) {
  ["create_options"]=>
  array(0) {
  }
  ["engine"]=>
  string(6) "InnoDB"
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "utf8"
  ["autoincrement"]=>
  string(2) "20"
}

# TO
array(3) {
  ["create_options"]=>
  array(0) {
  }
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "UTF8"
}
```

setting `charset` to `utf8mb3` in my config throws an error about unrecognized charset.  Are you suggesting I migrate the tables manually to `utf8mb3` and that this may resolve errors with the `charset: UTF8` config?

if it makes any difference, my database is set to `charset=utf8` and `collation=utf8_general_ci`.  I have yet to run a comprehensive check on app tables.

**Comment by greg0ire** [comment]
>  Are you suggesting I migrate the tables manually to utf8mb3 and that this may resolve errors with the charset: UTF8 config?

No, I thought your tables where already using that, as show by `SHOW CREATE TABLE`

> setting charset to utf8mb3 in my config throws an error about unrecognized charset.

What throws the error? The server? PDO? `doctrine/dbal`? Where does that uppercase `UTF8` come from? Your DSN maybe?

**Comment by arderyp** [comment]
upper case `charset: UTF8` comes from the symfony documentation I linked earlier.

`charset: utf8mb3` in config throws:

```
$ ./bin/console doctrine:migrations:diff

In ExceptionConverter.php line 119:
                                                                                     
  An exception occurred in the driver: SQLSTATE[HY000] [2019] Unknown character set  
                                                                                     

In Exception.php line 30:
                                                
  SQLSTATE[HY000] [2019] Unknown character set  
                                                

In Driver.php line 28:
                                                
  SQLSTATE[HY000] [2019] Unknown character set  
```

**Comment by greg0ire** [comment]
Well that's confusing to say the least :thinking:

**Comment by arderyp** [comment]
ok, I am making some progress.  If I change my config to `charset: utf8` (not `UTF8), it no longer generates a down migration for my test table.

I am still getting other down migrations, but that is for the handful of tables that are defined as `COLLATE `utf8_unicode_ci`` instead of `utf8_general_ci`.  So, I am guessing I could resolve my specific situation by using:

```
charset: utf8
  driver: pdo_mysql
  default_table_options:
    collation: utf8_general_ci
```
then manually creating `up()` migrations for my `utf8_unicode_ci` tables to `utf8_general_ci`.

However, there is still something wrong with the code. I;m now even more convinced of my proposal above that the issue may in fact not be with `down()` generating junk, but rather with `up()` not actually generating what it should (in my case, migrating my `utf8_unicode_ci` tables to `utf8_general_ci`)

There's also the remaining question, should `UTF8` and `utf8` be treated the same.  MySql seems to use the lower case, whereas Symfony docs (and users like me who followed it) use upper case.

**Comment by arderyp** [comment]
in other words, `down()` is responding to changes I make to my config, but `up()` does nothing in all cases.

**Comment by greg0ire** [comment]
> ok, I am making some progress. If I change my config to charset: utf8 (not `UTF8), it no longer generates a down migration for my test table.

Congrats!

> then manually creating up() migrations for my utf8_unicode_ci tables to utf8_general_ci.

Again, not a specialist, but I think I would recommend migrating to `utf8_unicode_ci`

> However, there is still something wrong with the code. I;m now even more convinced of my proposal above that the issue may in fact not be with down() generating junk, but rather with up() not actually generating what it should (in my case, migrating my utf8_unicode_ci tables to utf8_general_ci)

That was my thinking as well, and it's explained by https://github.com/doctrine/dbal/issues/4945 I think.


> There's also the remaining question, should UTF8 and utf8 be treated the same. MySql seems to use the lower case, whereas Symfony docs (and users like me who followed it) use upper case.

Good question. Using your MySQL client, can you try creating a table for both cases, then use `SHOW CREATE TABLE` on those? I'm suspecting that it will result in something normalized.

**Comment by arderyp** [comment]
@greg0ire sure I'm happy to do that, but can you be more explicit?  You want me to run the create at the mysql terminal?  Example command?

I can't really remember if I created my newer tables manually then generated Doctrine entities from that, or vice versa.

**Comment by greg0ire** [comment]
> You want me to run the create at the mysql terminal? Example command?

Yes

```sql
CREATE TABLE Foo (Bar INT NOT NULL) DEFAULT CHARACTER SET utf8;
CREATE TABLE Bar (Foo INT NOT NULL) DEFAULT CHARACTER SET UTF8;
SHOW CREATE TABLE Foo;
SHOW CREATE TABLE Bar;
```

**Comment by arderyp** [comment]
```
mysql> SHOW CREATE TABLE Foo;
+-------+-----------------------------------------------------------------------------------+
| Table | Create Table                                                                      |
+-------+-----------------------------------------------------------------------------------+
| Foo   | CREATE TABLE `Foo` (
  `Bar` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |
+-------+-----------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> SHOW CREATE TABLE Bar;
+-------+-----------------------------------------------------------------------------------+
| Table | Create Table                                                                      |
+-------+-----------------------------------------------------------------------------------+
| Bar   | CREATE TABLE `Bar` (
  `Foo` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |
+-------+-----------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by greg0ire** [comment]
Interesting. Can you also try `utf8mb3` ? That way we will now if the error message you got really came from the server or from PDO.

Anyway, I think you'll agree with me that `UTF8` should not be mentioned in any docs.

**Comment by arderyp** [comment]
for documentation, [this](https://github.com/doctrine/migrations/blob/3.4.x/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L115) works, and [this](https://github.com/doctrine/migrations/blob/3.4.x/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L104) does not.

Sequence:

- [Schema/Comparator::__call](https://github.com/doctrine/dbal/blob/3.3.x/src/Schema/Comparator.php#L54) ->
  - [Schema/Comparator::doCompareSchemas](https://github.com/doctrine/dbal/blob/3.3.x/src/Schema/Comparator.php#L86)
    - [MySQL/Comparator::diffTable](https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/MySQL/Comparator.php#L32)
      - back to parent [Schema/Comparator::diffTable](https://github.com/doctrine/dbal/blob/3.3.x/src/Schema/Comparator.php#L260)

I have not yet determined if the issue lies with `MySQL/Comparator::diffTable` or `Schema/Comparator::diffTable`

**Comment by arderyp** [comment]
Yes, it seems `UTF8` shouldn't be in the docs, but I wonder if the proper solution is for doctrine to convert it to `utf8`. But even that seems to map to `utf8mb3`, which isn't advisible according to your earlier posts.  Maybe there should either be a more sensible default (along what you outlined [here](https://github.com/doctrine/DoctrineBundle/pull/1471#issuecomment-1040780904)) or perhaps there should be no defaults and the implementer should be forced to explicitly define `charset` `default_table_options[charset]` and `default_table_options[collation]`, which should be reflected in symfony docs.

Anywho, you said "Can you also try utf8mb3"... what's that in reference to?  Setting that as my config charset or re-running the table creations using `utf8mb3` instead of `utf8`?

**Comment by greg0ire** [comment]
>  re-running the table creations using utf8mb3 instead of utf8?

Yes, for science. I'm wondering if you will get an error message this time.

**Comment by arderyp** [comment]
for science :clinking_glasses: 

```
mysql> CREATE TABLE Foo (Bar INT NOT NULL) DEFAULT CHARACTER SET utf8mb3;
Query OK, 0 rows affected, 1 warning (0.08 sec)

mysql> show create table Foo;
+-------+-----------------------------------------------------------------------------------+
| Table | Create Table                                                                      |
+-------+-----------------------------------------------------------------------------------+
| Foo   | CREATE TABLE `Foo` (
  `Bar` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 |
+-------+-----------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by arderyp** [comment]
@greg0ire unfortunately, I feel like I'm reaching the limit of my debugging capabilities here.

As far as I've gotten is tracking the issue to here: https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/MySQL/Comparator.php#L56

My live table schema is having it's table definition mapped properly to its columns:

```
# TABLE OPTIONS: var dump of $table->getOptions() in MySQL/Comparator::normalizeColumns
# for table that's getting down() migration
array(6) {
  ["create_options"]=>
  array(0) {
  }
  ["engine"]=>
  string(6) "InnoDB"
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "utf8"
  ["autoincrement"]=>
  string(2) "20"
  ["comment"]=>
  string(37) "List of applications in CEE's system."
}

# DEFAULTS: var dump of $defaults in MySQL/Comparator::normalizeColumns
# for table that's getting down() migration
array(2) {
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "utf8"
}

# COLUMN PLATFORM OPTIONS: var dump of $column->getPlatformOptions() in MySQL/Comparator::normalizeColumns
# for field "name" on table that's getting down() migration
array(2) {
  ["charset"]=>
  string(4) "utf8"
  ["collation"]=>
  string(15) "utf8_general_ci"
}

# DIFF: var dump of $diff in MySQL/Comparator::normalizeColumns
# for field "name" on table that's getting down() migration
array(0) {
}
```

However, the `charset` and `collation` from my configuration Table object are not being properly mapped to it's corresponding Column children:

```
# TABLE OPTIONS: var dump of $table->getOptions() in MySQL/Comparator::normalizeColumns
# for table that's getting down() migration
array(3) {
  ["create_options"]=>
  array(0) {
  }
  ["charset"]=>
  string(7) "utf8mb4"
  ["collation"]=>
  string(18) "utf8mb4_unicode_ci"
}

# DEFAULTS: var dump of $defaults in MySQL/Comparator::normalizeColumns
# for table that's getting down() migration
array(2) {
  ["collation"]=>
  string(15) "utf8_general_ci"
  ["charset"]=>
  string(4) "utf8"
}

# COLUMN PLATFORM OPTIONS: var dump of $column->getPlatformOptions() in MySQL/Comparator::normalizeColumns
# for field "name" on table that's getting down() migration
array(1) {
  ["version"]=>
  bool(false)
}

# DIFF: var dump of $diff in MySQL/Comparator::normalizeColumns
# for field "name" on table that's getting down() migration
array(1) {
  ["version"]=>
  bool(false)
}
```

I'm kind of at a dead end, but maybe this will give you and idea for where we should look next.

**Comment by dmaicher** [comment]
> thinking from what I read here, it is recommended to use `_unicode_` over `_general_`.
> 
> > So somehow it seems to be a mismatch between utf8_general_ci and utf8_unicode_ci?
> 
> I would expect `up()` to mention what is defined in your config, but for `down()`, I would expect it to mention whatever is introspected. If you use `SHOW CREATE TABLE address`, what do you get?

@greg0ire this is what I get

```
| address | CREATE TABLE `address` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `street` longtext COLLATE utf8_unicode_ci,
  `additional_info_1` longtext COLLATE utf8_unicode_ci,
  `additional_info_2` longtext COLLATE utf8_unicode_ci,
  `city` longtext COLLATE utf8_unicode_ci,
  `zip_code` longtext COLLATE utf8_unicode_ci,
  `country` longtext COLLATE utf8_unicode_ci,
  `latitude` longtext COLLATE utf8_unicode_ci,
  `longitude` longtext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
```

**Comment by greg0ire** [comment]
Ok so `down()` seems to behave well, in your case, since you instructed to use `utf8_general_ci`, `down()` is supposed to do the opposite of that and restore what you currently have, which is `utf8_unicode_ci`.

**Comment by dmaicher** [comment]
> Ok so `down()` seems to behave well, in your case, since you instructed to use `utf8_general_ci`, `down()` is supposed to do the opposite of that and restore what you currently have, which is `utf8_unicode_ci`.

Yes indeed. Just the empty `up()` is then probably a bug?

**Comment by greg0ire** [comment]
Yes, and I think it is that bug: https://github.com/doctrine/dbal/issues/4945

I don't understand why it affects only `up()` though.

**Comment by arderyp** [comment]
so @greg0ire do you suspect https://github.com/doctrine/dbal/issues/4945 fixed the broken `up()` situation @dmaicher and I are experiencing?

**Comment by arderyp** [comment]
@greg0ire the description of https://github.com/doctrine/dbal/issues/4945 seems to reflect the broken `up()` issues, so hopefully that fixes it.  If you need me to fig further just let me know.

**Comment by arderyp** [comment]
@greg0ire , given [this comment](https://github.com/doctrine/DoctrineBundle/pull/1471#issuecomment-1040780904)...

My mysql server is currently 5.7 but will be updated soon to 8.  I'm considering converting all tables/fields to `utf8mb4`/`utf8mb4_unicode_ci` now with a manually built migration to resolve this issue. However, since mysql 8 defaults to `utf8mb4_0900_ai_ci`(which both you and [this post](https://saveriomiroddi.github.io/An-in-depth-dbas-guide-to-migrating-a-mysql-database-from-the-utf8-to-the-utf8mb4-charset/#-collation-warning-) mention), I'm wondering how I should proceed.  

Should I migrate to `utf8mb4`/`utf8mb4_unicode_ci` now while on 5.7, or wait until mysql is upgraded to 8 then migrate to `utf8mb4`/`utf8mb4_0900_ai_ci`, or perhaps migrate now to `utf8mb4_unicode_ci` and then update to `utf8mb4_0900_ai_ci` when upgrading to 8.  It isn't entirely clear to me if using `utf8mb4`/`utf8mb4_unicode_ci` on mysql 8 would present a problem (the aforementioned post has an explicit warning about the collation setting, but I'm struggling to make sense of it).

Given that you know a great deal about this, I consider your insight valuable, if you have the time.  Thanks in advance.

**Comment by greg0ire** [comment]
> Given that you know a great deal about this, I consider your insight valuable, if you have the time. 

Actually I don't, I just skimmed through the posts I found. I never paid attention to collation until starting to work on this.
My current idea is
- `utf8` = `utf8mb3` bad proprietary collation, avoid it
- `utf8mb4` is what should have been called aliased to `utf8`, and should have been the default, and won't cause any issues on MySQL 8
- `utf8mb4_0900_ai_ci` is a cool new collation that provides accent insensitivity. Only you know if that feature would be interesting to you.

**Comment by arderyp** [comment]
Thanks for the feedback @greg0ire!
