### PR TITLE
Fix compat with repositories declared as lazy services

### LINKED ISSUE #1615: Compile error after introduction of LazyServiceEntityRepository
In our project (Symfony 6.2 and PHP 8.2) we had the following error with version 2.8.1 of the project:

  Compile Error: Declaration of Symfony\Component\VarExporter\LazyGhostTrait::createLazyGhost(Closure|array $initializer, ?array $skippedProperties = null, ?ContainerEitUOS3\UserRepositoryGhostAe7ae8b $instance = null): ContainerEitUOS3\MyProject_KernelTestDebugContainer must be compatible with Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository::createLazyGhost(Closure|array $initializer, ?array $skippedProperties = null, ?Doctrine\Bundle\DoctrineBundle\Repository\LazyServiceEntityRepository $instance = null): ContainerEitUOS3\MyProject_KernelTestDebugContainer

For the time being we've locked the version of `doctrine/doctrine-bundle` down to 2.8.0.

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Needed to fully fix #1615

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
~I would gladly accept help to fix the failures on the CI :pray:~
Remaining failures unrelated.

File: Tests/Repository/ServiceEntityRepositoryTest.php [hunk 1]
```diff
@@ -33,4 +35,15 @@ public function testConstructorThrowsExceptionWhenNoManagerFound(): void
...
         $repo->getClassName();
     }
+
+    /** @requires function \Symfony\Component\VarExporter\ProxyHelper::generateLazyGhost */
+    public function testConstructInitializesWhenImplementingLazyObjectInterface(): void
+    {
+        $registry = $this->getMockBuilder(ManagerRegistry::class)->getMock();
+        $this->expectException(LogicException::class);
+
+        new class ($registry, TestEntity::class) extends ServiceEntityRepository implements LazyObjectInterface {
```
Comment (greg0ire) [inline Tests/Repository/ServiceEntityRepositoryTest.php:49]: You can copy line 34 here I think, and add another suppress annotation for `MissingDependency`, since Psalm runs with 7.4 (I'm assuming there is no way to get `LazyObjectInterface` for that version of PHP)

Comment (nicolas-grekas) [reply Tests/Repository/ServiceEntityRepositoryTest.php:49]: that did it, thanks. Remaining failures are unrelated.

**Review by stof — APPROVED** [review]

**Review by ostrolucky — APPROVED** [review]
