### PR TITLE
Fix configuration inheritance to not override default connection/EM values

### LINKED ISSUE #1337: `default_entity_manager` config param is not inherited from parent config file
This line in Configuratation:
https://github.com/doctrine/DoctrineBundle/blob/09339f7df6fc620ce805f52ca0c7424543d30515/DependencyInjection/Configuration.php#L376

makes `default_entity_manager` (=<some_none_default_value>) param defined in `config/packages/doctrine.yml`
been overriden by `config/packages/prod/doctrine.yml` without this option.
Instead of the value from `config/packages/doctirne.yml` we have `default` value.
Which is conter-intuitive and took a couple of time to investigate mapping issues.

Example:
```yaml
#c onfig/packages/doctrine.yml
doctrine:
  # ...
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: app
        entity_managers:
            app:
               # ...
            module:
               #...
```

```yaml
#config/packages/prod/doctrine.yml
# The default one, generated by flex

doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
```

Expected: `app`
Given: `default`

### PR DESCRIPTION
**Pull request by tucksaun**
Hi there!

I recently unveiled a weird behavior when doing some cleanup on a project I work on.
Long story short, we have several connections, use a different name than `default` for the main one, and because we have config files defining only `doctrine.dbal.types`, the `default_connection` ends up being reset to `default`. 

While trying to fix this I realized this is similar to #1337 (just another section of the config really), so I try to fix #1337 at the same time (therefore being an alternative to #1356).

The true nature of the fix is mostly not to run the custom pre-normalization process but then this makes the default empty configuration not work anymore.
So we move the side effect of this process (creating an empty 'default' connection configuration) out in the Extension and we rerun the normalization process again so that the default values for connections and entity manager get resolved properly.

This should be considered a bugfix, but I'm not really sure which branch to target in that case, let me know if you want me to rebase and target another branch instead

### CODE REVIEW

File: Tests/DependencyInjection/DoctrineExtensionTest.php [hunk 1]
```diff
@@ -695,6 +709,27 @@ public function testOverwriteEntityAliases(): void
...
+            self::markTestSkipped('This test requires ORM');
+        }
+
+        $container = $this->getContainer();
+        $extension = new DoctrineExtension();
+
+        $config        = BundleConfigurationBuilder::createBuilder()
+            ->addBaseConnection()
+            ->build();
+        $config['orm'] = ['default_entity_manager' => 'app', 'entity_managers' => ['app' => ['mappings' => ['YamlBundle' => ['alias' => 'yml']]]]];
```
Comment (ostrolucky) [inline Tests/DependencyInjection/DoctrineExtensionTest.php]: Instead of using both config builder and plain array, let's stick to one approach. If you can't use config  builder, switch to plain array fully.

File: DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -72,17 +75,29 @@ public function getConfigTreeBuilder(): TreeBuilder
...
+                        if (! is_array($v)) {
+                            return false;
+                        }
+
+                        if (array_key_exists('connections', $v) || array_key_exists('connection', $v)) {
+                            return false;
+                        }
+
+                        // Is there actually anything to use once excluded keys considered?
+                        return ! empty(array_filter($v, static function ($key) use ($excludedKeys) {
```
Comment (ostrolucky) [inline DependencyInjection/Configuration.php]: This seems like you reimplemented array_diff_key. Let's also get rid of !empty(), it can be replaced by (bool).

File: DependencyInjection/Configuration.php [hunk 3]
```diff
@@ -380,30 +394,47 @@ private function configureDbalDriverNode(ArrayNodeDefinition $node): void
...
                     ->beforeNormalization()
-                        ->ifTrue(static function ($v) {
+                        ->ifTrue(static function ($v) use ($excludedKeys) {
                             if (! empty($v) && ! class_exists(EntityManager::class)) {
                                 throw new LogicException('The doctrine/orm package is required when the doctrine.orm config is set.');
                             }
 
-                            return $v === null || (is_array($v) && ! array_key_exists('entity_managers', $v) && ! array_key_exists('entity_manager', $v));
+                            if ($v === null) {
+                                return false;
```
Comment (ostrolucky) [inline DependencyInjection/Configuration.php]: This seems like you reversed the condition. Can you please ensure line is covered by tests?

File: DependencyInjection/DoctrineExtension.php [hunk 4]
```diff
@@ -104,6 +120,20 @@ public function load(array $configs, ContainerBuilder $container)
...
+                    'orm' => [
+                        'entity_managers' => [
+                            ($config['orm']['default_entity_manager'] ?? 'default') => [],
+                        ],
+                    ],
+                ],
+            ], $configs));
+        }
+
         $this->ormLoad($config['orm'], $container);
```
Comment (ostrolucky) [inline DependencyInjection/DoctrineExtension.php]: Let's move above to ormLoad method

File: DependencyInjection/DoctrineExtension.php [hunk 5]
```diff
@@ -91,6 +92,21 @@ public function load(array $configs, ContainerBuilder $container)
...
+                        'dbal' => [
+                            'connections' => [
+                                ($config['dbal']['default_connection'] ?? 'default') => [],
+                            ],
+                        ],
+                    ],
+                ], $configs));
+            }
+
             $this->dbalLoad($config['dbal'], $container);
```
Comment (ostrolucky) [inline DependencyInjection/DoctrineExtension.php:96]: Let's move above to dbalLoad method

File: DependencyInjection/DoctrineExtension.php [hunk 6]
```diff
@@ -91,6 +92,21 @@ public function load(array $configs, ContainerBuilder $container)
         $config        = $this->processConfiguration($configuration, $configs);
 
         if (! empty($config['dbal'])) {
+            // if no DB connection defined, prepend an empty one for the default
```
Comment (ostrolucky) [inline DependencyInjection/DoctrineExtension.php]: Does it actually need to prepend instead of append?

File: DependencyInjection/DoctrineExtension.php [hunk 7]
```diff
@@ -91,6 +92,21 @@ public function load(array $configs, ContainerBuilder $container)
...
+            if (empty($config['dbal']['connections'])) {
+                $config = $this->processConfiguration($configuration, array_merge([
+                    [
+                        'dbal' => [
+                            'connections' => [
+                                ($config['dbal']['default_connection'] ?? 'default') => [],
+                            ],
+                        ],
+                    ],
+                ], $configs));
```
Comment (ostrolucky) [inline DependencyInjection/DoctrineExtension.php]: I don't like how verbose these are, let's do something like
```suggestion
                $configs[] = ['dbal' => ['connections' => [($config['dbal']['default_connection'] ?? 'default') => []]]];
                $config    = $this->processConfiguration($configuration, $configs);
```
instead

**Review by ostrolucky — CHANGES_REQUESTED** [review]
This was a can of worms last time, so I think I will need review from someone else as well.

File: Tests/DependencyInjection/DoctrineExtensionTest.php (hunk 1 above)
Comment (tucksaun) [reply Tests/DependencyInjection/DoctrineExtensionTest.php]: I'm fine with a plain array, I just mimicked the logic from above which is done this way I guess to not rely on knowing the default dbal configuration in an EM related test 🤷

File: DependencyInjection/Configuration.php (hunk 2 above)
Comment (tucksaun) [reply DependencyInjection/Configuration.php]: 🤦
let's keep that between you and me 😅

File: DependencyInjection/Configuration.php (hunk 3 above)
Comment (tucksaun) [reply DependencyInjection/Configuration.php]: Yep, I reversed it because a null value here was interesting to get into the normalization callback that would create the empty default entity manager configuration which we are now doing in the Extension.
This what not covered before but I added a test case.
And because now we are now sure to enter the normalization callback with an array I removed cast to an array there

File: DependencyInjection/DoctrineExtension.php (hunk 4 above)
Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php]: not really possible atm because it needs access to the original `$configs`.

File: DependencyInjection/DoctrineExtension.php (hunk 5 above)
Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php:96]: not really possible atm because it needs access to the original `$configs`.

File: DependencyInjection/DoctrineExtension.php (hunk 6 above)
Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php]: good question...
I would say that it does not matter given it only adds an empty connection array and that there's no change it would get overridden because otherwise, we would not be in that case.
but my gut tells me pre-pending is better because it's closer to the concept of `processConfiguration`

Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php]: but now that I read your comment bellow your question makes more sense to me...
test passes so I guess we are good to go

File: DependencyInjection/DoctrineExtension.php (hunk 7 above)
Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php]: done 👍

**Comment by tucksaun** [comment]
> This was a can of worms last time, so I think I will need review from someone else as well.

Yeah, I've read that 😞 
I guess @nicolas-grekas and @stof would be great ones for reviewing this PR

**Comment by tucksaun** [comment]
@ostrolucky thank you for the review btw!
all comments (except dbalLoad/ormLoad) should have been addressed 💪

**Comment by stof** [comment]
could we do the checks on default connection and default entity manager together at the beginning, to process the configuration only twice instead of 3 times ? Otherwise, we might report deprecations 3 times when a deprecated setting is used.

**Comment by tucksaun** [comment]
Good call @stof !
We could then wrap this logic into processConfiguration. Wdyt?

**Comment by ostrolucky** [comment]
Good idea I think

File: DependencyInjection/DoctrineExtension.php [hunk 8]
```diff
@@ -107,6 +109,40 @@ public function load(array $configs, ContainerBuilder $container)
...
+     * default values for each.
+     *
+     * @param array<array<mixed>> $configs
+     *
+     * @return array<mixed>
+     */
+    private function processConfigurationPrependingDefaults(ConfigurationInterface $configuration, array $configs): array
+    {
+        $config      = $this->processConfiguration($configuration, $configs);
+        $configToAdd = [];
```
Comment (ostrolucky) [inline DependencyInjection/DoctrineExtension.php:124]: Why this instead of doing `$configs[] =` ?

Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php:124]: if we want to call `processConfiguration` a second time only when required we need to track if some configuration has been added or not.
if we directly append to `configs` we can't really tell 🤷

**Review by ostrolucky — APPROVED** [review]

File: DependencyInjection/DoctrineExtension.php (hunk 8 above)
Comment (tucksaun) [reply DependencyInjection/DoctrineExtension.php:124]: But thinking about it, we can use a Boolean value to track this if you prefer

Comment (ostrolucky) [reply DependencyInjection/DoctrineExtension.php:124]: no it's ok

**Review by dmaicher — APPROVED** [review]
LGTM and also tested it quickly on one of my apps: no issues :+1:
