### PR TITLE
Fix second level cache compatibility layer

### LINKED ISSUE #1364: second level cache is broken
**DoctrineBundle affected**: 2.4.1

**Description**
After the `сomposer update` and updates `doctrine/doctrine-bundles` to 2.4, there is a fatal error.  
Before updating the error package was not.

**How to reproduce**
```yaml
// config/packages/cache.yaml
framework:
    cache:
        # Redis
        app: cache.adapter.redis_tag_aware
        default_redis_provider: redis://localhost
```

```yaml
// config/packages/doctrine_second_cache.yaml
doctrine:
    orm:
        second_level_cache:
            enabled: true
            region_cache_driver:
                type: pool
                pool: doctrine.second_level_cache_pool

framework:
    cache:
        pools:
            doctrine.second_level_cache_pool:
                adapter:          cache.app
                default_lifetime: 60
```

**Additional context**
```bash
$ bin/console cache:clear
TypeError {#568
  #message: "Argument 2 passed to Doctrine\ORM\Cache\DefaultCacheFactory::__construct() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\TraceableTagAwareAdapter given, called in /tmp/sf5.2/var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php on line 665"
  #code: 0
  #file: "./vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php"
  #line: 65
  trace: {
    ./vendor/doctrine/orm/lib/Doctrine/ORM/Cache/DefaultCacheFactory.php:65 { …}
    ./var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php:665 {
      ContainerVpzExal\App_KernelDevDebugContainer->getDoctrine_Orm_DefaultEntityManagerService($lazyLoad = true)^
      › $b->setCacheLogger($c);
      › $b->setCacheFactory(new \Doctrine\ORM\Cache\DefaultCacheFactory($d, ($this->privates['doctrine.second_level_cache_pool'] ?? $this->getDoctrine_SecondLevelCachePoolService())));
      › $b->setRegionsConfiguration($d);
    }
    ./var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php:612 { …}
    ./var/cache/dev/ContainerVpzExal/EntityManager_9a5be93.php:239 { …}
    ./var/cache/dev/ContainerVpzExal/EntityManager_9a5be93.php:239 { …}
    ./vendor/symfony/doctrine-bridge/CacheWarmer/ProxyCacheWarmer.php:54 { …}
    ./vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:98 { …}
    ./vendor/symfony/http-kernel/Kernel.php:580 { …}
    ./vendor/symfony/http-kernel/Kernel.php:780 { …}
    ./vendor/symfony/http-kernel/Kernel.php:121 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:166 { …}
    ./bin/console:43 { …}
  }
}
2021-06-01T20:38:15+00:00 [critical] Uncaught Error: Argument 2 passed to Doctrine\ORM\Cache\DefaultCacheFactory::__construct() must implement interface Doctrine\Common\Cache\Cache, instance of Symfony\Component\Cache\Adapter\TraceableTagAwareAdapter given, called in /tmp/sf5.2/var/cache/dev/ContainerVpzExal/App_KernelDevDebugContainer.php on line 665
```

### PR DESCRIPTION
**Pull request by alcaeus**
Fixes #1364.

Our compatibility layer forgot to take into account second-level caches, which aren't set on the configuration directly but rather in a separate factory. This PR fixes this issue and adds a functional test that fetches an entity manager for each cache configuration we have: for each metadata, query, result, and second-level cache we test with the pool, psr-6 service, and doctrine/cache type. For metadata, we also test without a metadata cache configured.

### CODE REVIEW

File: Tests/DependencyInjection/DoctrineExtensionTest.php [hunk 1]
```diff
@@ -1081,9 +1081,7 @@ public function testShardManager(): void
         $this->assertEquals($managerClass, $bazManagerDef->getClass());
     }
 
-    /**
-     * @requires PHP 8
-     */
+    /** @requires PHP 8 */
```
Comment (stof) [inline Tests/DependencyInjection/DoctrineExtensionTest.php]: This is reverting https://github.com/doctrine/DoctrineBundle/pull/1358. Is it intended ?

Comment (alcaeus) [reply Tests/DependencyInjection/DoctrineExtensionTest.php]: No, it is not. Thanks for pointing this out!

File: Tests/DependencyInjection/DoctrineExtensionTest.php [hunk 2]
```diff
@@ -1081,6 +1081,9 @@ public function testShardManager(): void
         $this->assertEquals($managerClass, $bazManagerDef->getClass());
     }
 
+    // Disabled to prevent changing the comment below to a single-line annotation
+    // phpcs:disable SlevomatCodingStandard.Commenting.RequireOneLineDocComment.MultiLineDocComment
+
```
Comment (alcaeus) [inline Tests/DependencyInjection/DoctrineExtensionTest.php:1086]: PHPUnit does not seem to understand one-line annotations, so we need to disable the sniff to avoid phpcbf changing this back.

File: Tests/DependencyInjection/AbstractDoctrineExtensionTest.php [hunk 3]
```diff
@@ -735,7 +850,7 @@ public function testSecondLevelCache(): void
         $this->assertDICDefinitionClass($myEntityRegionDef, '%doctrine.orm.second_level_cache.default_region.class%');
         $this->assertDICDefinitionClass($loggerChainDef, '%doctrine.orm.second_level_cache.logger_chain.class%');
         $this->assertDICDefinitionClass($loggerStatisticsDef, '%doctrine.orm.second_level_cache.logger_statistics.class%');
-        $this->assertDICDefinitionClass($cacheDriverDef, ArrayAdapter::class);
+        $this->assertDICDefinitionClass($cacheDriverDef, CacheProvider::class);
```
Comment (alcaeus) [inline Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:853]: On second thought, having to change this should probably have alerted us to the  bug. Oh well 🤷‍♂️

File: Tests/DependencyInjection/DoctrineExtensionTest.php (hunk 2 above)
Comment (stof) [reply Tests/DependencyInjection/DoctrineExtensionTest.php:1086]: can we instead disable that sniff for the whole Tests folder through the config, to avoid introducing similar issues in the future when using PHPUnit annotations on other tests ?

File: DependencyInjection/Compiler/CacheCompatibilityPass.php [hunk 4]
```diff
@@ -29,44 +31,84 @@ public function process(ContainerBuilder $container): void
...
-                $targetFactory = DoctrineProvider::class;
+            $factoryDefinition = $methodCall[1][0];
+            assert($factoryDefinition instanceof Definition);
+            break;
+        }
 
-                if ($shouldBePsr6) {
-                    $targetClass   = CacheItemPoolInterface::class;
-                    $targetFactory = CacheAdapter::class;
+        $aliasId      = (string) $factoryDefinition->getArgument(1);
```
Comment (ostrolucky) [inline DependencyInjection/Compiler/CacheCompatibilityPass.php]: From SA perspective, `$factoryDefinition` may not exist. Everything below this line, including this line, should be moved inside `foreach`, where existence of `$factoryDefinition` is guaranteed. I would suggest
```php
foreach ($slcConfigDefinition->getMethodCalls() as $methodCall) {      
    if ($methodCall[0] !== 'setCacheFactory') {
        continue;
    }
    $factoryDefinition = $methodCall[1][0];
    assert($factoryDefinition instanceof Definition);
    $aliasId = (string) $factoryDefinition->getArgument(1);
    $this->wrapIfNecessary($container, $aliasId, (string) $container->getAlias($aliasId), false);
    break;
}
```

File: DependencyInjection/Compiler/CacheCompatibilityPass.php [hunk 5]
```diff
@@ -29,44 +31,84 @@ public function process(ContainerBuilder $container): void
     {
         foreach (array_keys($container->findTaggedServiceIds(self::CONFIGURATION_TAG)) as $id) {
             foreach ($container->getDefinition($id)->getMethodCalls() as $methodCall) {
+                if ($methodCall[0] === 'setSecondLevelCacheConfiguration') {
+                    $slcConfigDefinition = $methodCall[1][0];
+                    $this->updateSecondLevelCache($container, $slcConfigDefinition);
```
Comment (ostrolucky) [inline DependencyInjection/Compiler/CacheCompatibilityPass.php]: I would inline that 
```php
                    $this->updateSecondLevelCache($container, $methodCall[1][0]);
```

**Review by dmaicher — APPROVED** [review]
LGTM :+1:

File: Tests/DependencyInjection/DoctrineExtensionTest.php (hunk 2 above)
Comment (ostrolucky) [reply Tests/DependencyInjection/DoctrineExtensionTest.php:1086]: I would rather bug was fixed in phpunit

File: Tests/DependencyInjection/AbstractDoctrineExtensionTest.php [hunk 6]
```diff
@@ -1281,7 +1396,6 @@ private function loadContainer(
     ): ContainerBuilder {
         $container = $this->getContainer($bundles);
         $container->registerExtension(new DoctrineExtension());
-        $container->addCompilerPass(new CacheCompatibilityPass());
```
Comment (ostrolucky) [inline Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:1284]: This seems contraproductive. It means we still don't have a test which checks our cache compatibility layer works with second level cache.

File: Tests/DependencyInjection/DoctrineExtensionTest.php (hunk 2 above)
Comment (stof) [reply Tests/DependencyInjection/DoctrineExtensionTest.php:1086]: long term, indeed.

Comment (greg0ire) [reply Tests/DependencyInjection/DoctrineExtensionTest.php:1086]: Fixed in https://github.com/sebastianbergmann/phpunit/pull/4693 , thanks @ostrolucky !

File: Tests/DependencyInjection/AbstractDoctrineExtensionTest.php (hunk 6 above)
Comment (ostrolucky) [reply Tests/DependencyInjection/AbstractDoctrineExtensionTest.php:1284]: I see now that it was removed because it's already included in `compileContainer` function

**Review by ostrolucky — APPROVED** [review]
