### PR TITLE
Fix doctrine:database:create and doctrine:database:drop for Postgresql on DBAL 4.x

### LINKED ISSUE #1757: Create and drop PostgreSQL database fails
Hello,
With ORM 3, `doctrine:database:create` and `doctrine:database:drop` failed.

### PR DESCRIPTION
**Pull request by ostrolucky**
Ref https://github.com/doctrine/dbal/pull/5705
Fixes #1757

### CODE REVIEW

File: Command/CreateDatabaseDoctrineCommand.php [hunk 1]
```diff
@@ -64,6 +65,10 @@ protected function execute(InputInterface $input, OutputInterface $output): int
         /** @psalm-suppress InvalidArrayOffset Need to be compatible with DBAL < 4, which still has `$params['url']` */
         unset($params['dbname'], $params['path'], $params['url']);
 
+        if ($connection->getDatabasePlatform() instanceof PostgreSQLPlatform) {
+            $params['dbname'] = 'postgres';
+        }
```
Comment (greg0ire) [inline Command/CreateDatabaseDoctrineCommand.php:70]: Why do we unset `dbname` on line 66, only to set it again here? Also, I don't understand the comment on line 64, should it read "as we have already extracted" instead of "and we have already extracted"?

Comment (ostrolucky) [reply Command/CreateDatabaseDoctrineCommand.php:70]: For the first point, it's because I assume unsetting dbname might still be needed for other db platforms. For the second point: I guess so.

**Review by greg0ire — APPROVED** [review]
